#pragma once

#pragma pack(push, 1)

#ifndef DIRECTDRAW_VERSION
typedef void* LPDIRECTDRAWSURFACE;
typedef void* LPDIRECTDRAWCLIPPER;
#endif

typedef int DatalinkID;
typedef int Vert;
typedef void HSV;
typedef void EdgeScan;
typedef void NCSprites;
typedef void BorderSizing;
typedef void BoxSpriteParams;
typedef void ExtDirectDraw;
typedef void ServiceList;
typedef void ServiceStruct;
typedef void SessionStruct;
typedef void NetThreadInfo;

struct Win;
struct Menu;
struct Buffer;
struct Scroll;
struct PullDown;

struct StringStructData {
    void* vtable;
    char* text;
    int32_t field_8;
    int32_t field_C;
    void* field_10;
    void* field_14;
};

struct StringStructNode {
    void* vtable;
    int32_t id;
    StringStructData* data;
    StringStructNode* next;
    StringStructNode* prev;
    void* field_14;
    void* field_18;
};

struct StringStruct {
    void* vtable;
    void* type_desc;
    StringStructNode* head;
    StringStructNode* cursor;
    int32_t count;
    uint32_t position;
    uint32_t flags;
    char* src_text;
    int32_t field_20;
    int32_t field_24;
    int32_t field_28;
    int32_t field_2C;
};

struct StringList : StringStruct {};

struct Heap {
    int err_flags;
    int base_ptr;
    void* current_ptr;
    int base_size;
    int free_size;
};

struct TexHeap {
    int base_ptr;
    int base_size;
    void* current_ptr;
    uint32_t count;
};

struct SpotNode {
    RECT rect;
    int type;
    int position;
};

struct Spot {
    SpotNode* spots;
    int max_count;
    int cur_count;
};

struct RenderCache {
    uint8_t brightness[4];
    uint8_t altitude[5];
    uint8_t flags;
    uint16_t altflags;
};

struct FileData {
    char filename[260];
    int field_104;
    int field_108;
    int field_10C;
    int field_110;
    int field_114;
};

struct Filemap {
    LPVOID mapViewAddr;
    HANDLE hFile;
    HANDLE hFileMap;
    DWORD fileSize;
};

struct Label {
    char** labels;
    int label_count;
};

struct Strings {
    Heap oMemAllocator;
    int fAllocated;
};

struct WinListItem {
    int field_0;
    void* pItem;
    int field_8;
    WinListItem* pPrev;
    WinListItem* pNext;
    int field_14;
    int field_18;
};

struct WinList {
    void* vtable;
    WinListItem* pFirst;
    WinListItem* pCurrent;
    int iCount;
    int iCurrent;
    Heap* poMemAllocator;
};

struct TextureStore {
    int field_0;
    int field_4;
    int field_8[148];
    int field_258;
    int field_25C;
};

struct SquareLock {
    int x;
    int y;
    uint32_t flags;
};

struct PlayerLock {
    uint8_t flags[4];
    SquareLock lock[2];
};

struct Lock {
    PlayerLock plr_lock[8];
    int field_E0;
    int field_E4;
    int field_E8;
};

struct DeletionItem {
    uint8_t flags[4];
    int type_id;
    uint16_t count;
    int16_t veh_ids[25];
};

struct DeletionList {
    DeletionItem items[24];
    int cur_type_id;
};

struct Time {
    int field_0;
    UINT_PTR idEvent;
    void (__cdecl *cb_daemon)(int);
    void (__cdecl *cb_timer)(int, int);
    int cb_param2;
    int cb_param1;
    uint32_t delay;
    int pending;
    uint32_t resolution;
    int field_24;
};

struct Font {
    int field_0;
    int flags;
    HFONT fontObj;
    int lineHeight;
    int height;
    int internalLeading;
    int ascent;
    int descent;
    int field_20;
    char* fontFileName;
};

struct FontQueue {
    Font fonts[3];
    int fontHeight[3];
    int fontStyle[3];
    int fontOrder[3];
    Font* fontActive;
};

struct Sound {
    void* vtable;
    int volume;
    int pan;
    int field_C;
    int field_10;
    int field_14;
    int field_18;
    int field_1C;
    int field_20;
    int field_24;
    int field_28;
    int field_2C;
    int loop_state;
    int delay;
    int fade;
    int field_3C;
    int flags;
    int field_44;
    int field_48;
    char* fname;
    int sound_type;
};

struct Wave : Sound {
    int field_54;
    int pitch;
    float reverb_mix;
    int ms_length;
    int field_64;
    int field_68;
};

struct Effect : Wave {};

struct PaletteInternal {
    int field_0;
    Time* ptrTime;
    BYTE field_8;
    BYTE field_9;
    BYTE field_A;
    BYTE field_B;
    void* field_C;
};

struct Palette {
    PALETTEENTRY colors[256];
    int seed;
    PaletteInternal paletteInternal[5];
};

struct PCXHeader {
    BYTE Identifier;
    BYTE Version;
    BYTE Encoding;
    BYTE BitsPerPixel;
    WORD XStart;
    WORD YStart;
    WORD XEnd;
    WORD YEnd;
    WORD HorzRes;
    WORD VertRes;
    BYTE Palette[48];
    BYTE Reserved1;
    BYTE NumBitPlanes;
    WORD BytesPerLine;
    WORD PaletteType;
    WORD HorzScreenSize;
    WORD VertScreenSize;
    BYTE Reserved2[54];
};

struct CavMatFlt {
    float values[3][3];
};

struct CavVecFlt {
    float x;
    float y;
    float z;
};

struct CavVecInt {
    int x;
    int y;
    int z;
};

struct CaviarItem {
    int field_0;
    int field_4;
};

struct CaviarData {
    int field_0;
    int field_4;
    int field_8;
};

struct Caviar {
    int field_0;
    int caviar_flags;
    int field_8;
    int field_C;
    int field_10;
    Buffer* target;
    int field_18;
    int prev_object_count;
    int render_pending;
    void* object_data_ptr;
    void* object_item_ptr;
    CavVecFlt scene_position;
    CavMatFlt scene_matrix;
    float scene_scale;
    CavVecFlt light_vector;
    CavVecFlt shadow_vector;
    int field_78;
    int field_7C;
    int field_80;
    int field_84;
    int field_88;
    int field_8C;
    int field_90;
    int field_94;
    int field_98;
    int field_9C;
    int field_A0;
    uint8_t shadow_enabled;
    CavVecInt camera_position;
    CavMatFlt camera_matrix;
    float zoom_scale;
    float world_vals[5];
    float src_x0;
    float src_y0;
    float src_x1;
    float src_y1;
    float view_x;
    float view_y;
    uint8_t padding[3];
    float view_dist;
    CaviarItem object_item[200];
    CaviarData object_data[200];
    int object_shade[200];
    uint32_t object_count;
};

struct Buffer {
    void* vtable;
    int field_4;
    int (__cdecl *cb_scroll)(char* text, int x, int y, int char_count);
    void (__cdecl *cb_entry)(int entry_id, int entry_type);
    int indent;
    int indentWork;
    int lineCount;
    int flags;
    RECT clipRect;
    RECT sizeRect;
    int field_40;
    int field_44;
    int field_48;
    int field_4C;
    uint8_t* data;
    void* ppvBits;
    LPDIRECTDRAWSURFACE ddSurface;
    LPDIRECTDRAWCLIPPER ddClipper;
    HDC hdcSurface;
    HDC hdcCompatible;
    int hdcLockCount;
    int dataLockCount;
    HRGN hClipRgn;
    HBITMAP hOldBitmap;
    HBITMAP hBitmap;
    BITMAPINFOHEADER bmiHeader;
    RGBQUAD bmiColors[256];
    int paletteSeed;
    int pitch;
    int linkCount;
    Spot linkSpots;
    char* linkTargets[20];
    int field_50C;
    int fontIndexWrite;
    int fontIndexBreak;
    int fontIndexMeasure;
    int linkState;
    int markupEnabled;
    int tildeEscapeEnabled;
    int tildeColorIndex;
    Font* font1;
    Font* font2;
    Font* font3;
    Font* font4;
    int textColor1;
    int textColor2;
    int textColor3;
    int textColorHyper;
    int shadowColor1;
    int shadowColor2;
    int shadowColor3;
    int shadowColorHyper;
    int shadowX1;
    int shadowX2;
    int shadowX3;
    int shadowXHyper;
    int shadowY1;
    int shadowY2;
    int shadowY3;
    int shadowYHyper;
    int field_57C;
    int paletteBase;
    Palette* palette;
};

struct Sprite {
    char* filename;
    uint8_t* data;
    uint8_t color_index[4];
    int pitch;
    int clip_width;
    int clip_height;
    int width;
    int height;
    int offset_x;
    int offset_y;
    int is_tex_heap;
};

struct Texture {
    uint8_t* data;
    int width;
    int height;
    int field_C;
    int field_10;
    int field_14;
    int field_18;
    int field_1C;
    int field_20;
    int field_24;
    int field_28;
    int field_2C;
    int field_30;
    int field_34;
    int field_38;
    int field_3C;
    int field_40;
    int field_44;
    int field_48;
    int field_4C;
    int field_50;
    int field_54;
    int field_58;
    int field_5C;
    int field_60;
    int field_64;
    int field_68;
    int is_tex_heap;
};

struct Flic {
    int field_0;
    Buffer buffer;
    int field_58C;
    int field_590;
    int field_594;
    int field_598;
    int field_59C;
    int field_5A0;
    int field_5A4;
    Buffer* buffer2;
    int field_5AC;
    int field_5B0;
    int field_5B4;
    FILE* file;
    Palette palette;
    int field_A10;
    int field_A14[32];
    int field_A94;
    int field_A98;
    int field_A9C;
    int field_AA0;
    int field_AA4;
    int field_AA8;
    int field_AAC;
    int field_AB0;
    int field_AB4[4];
    int field_AC4[4];
    int field_AD4[4];
};

struct AutoSound {
    void* vtable;
    int field_4;
    int field_8;
    int field_C;
    int field_10;
    int field_14;
    int field_18;
    int field_1C;
    int field_20;
    int field_24;
    int field_28;
    int field_2C;
    int field_30;
    int field_34;
    int field_38;
    int field_3C;
    int field_40;
    int field_44;
    int field_48;
    int field_4C;
    int field_50;
    int field_54;
    int field_58;
    int field_5C;
    int field_60;
    int field_64;
    int field_68;
    int field_6C;
    int field_70;
    int field_74;
    int field_78;
    int field_7C;
    int field_80;
    int field_84;
    int field_88;
    int field_8C;
    int field_90;
    int field_94;
};

struct Win : AutoSound {
    uint32_t winflags;
    uint32_t winstate;
    int field_A0;
    int field_A4;
    Win* winbase;
    int field_AC;
    int field_B0;
    Buffer* winbuffer1;
    Buffer* winbuffer2;
    Buffer* winbuffer3;
    Buffer* winbuffer4;
    Win* parent;
    WinList winlist;
    char* caption;
    Win* button_minimize;
    Win* button_zoom;
    Win* button_close;
    Menu* menu;
    int field_F4;
    Font* caption_font;
    Buffer* tilebuffer;
    int field_100;
    int field_104;
    int field_108;
    int field_10C;
    int field_110;
    int field_114;
    int field_118;
    int field_11C;
    int field_120;
    int field_124;
    int field_128;
    Buffer* backbuffer;
    int field_130;
    int field_134;
    int field_138;
    RECT winrect1;
    RECT winrect2;
    RECT winrect3;
    int field_16C;
    int field_170;
    int field_174;
    int field_178;
    int field_17C;
    int field_180;
    int field_184;
    Sprite* sprite_cursor;
    int field_18C;
    int field_190;
    HCURSOR* phCursor;
    int nCursorName;
    int field_19C;
    int field_1A0;
    Win* children[150];
    int child_count;
    void (__cdecl *cb_win_resize)(int, int);
    void (__cdecl *cb_win_close)();
    void (__cdecl *cb_win_mouse_move)(int, int);
    void (__cdecl *cb_win_l_button_down)(int, int);
    void (__cdecl *cb_win_r_button_down)(int, int);
    void (__cdecl *cb_win_l_button_up)(int, int);
    void (__cdecl *cb_win_l_button_down_alt)(int, int);
    void (__cdecl *cb_win_l_button_up_alt)(int, int);
    void (__cdecl *cb_win_r_button_up)(int, int);
    void (__cdecl *cb_win_r_button_down_alt)(int, int);
    void (__cdecl *cb_win_r_button_up_alt)(int, int);
    int (__cdecl *cb_win_key_click)(int, int);
    int (__cdecl *cb_win_key_down)(int);
    int (__cdecl *cb_win_key_up)(int);
    int field_438;
    Scroll* scroll_vert;
    Scroll* scroll_horz;
};

struct GraphicWin : Win {
    Buffer oCanvas;
    Sprite* spWinTopLeft;
    Sprite* spWinBottomLeft;
    Sprite* spWinTopRight;
    Sprite* spWinBottomRight;
    Sprite* spWinLeft;
    Sprite* spWinRight;
    Sprite* spWinBottom;
    Sprite* spWinTop;
    Sprite* spWinNcTopLeft;
    Sprite* spWinNcTopRight;
    Sprite* spWinNcTop;
    Sprite* spWinOvTopLeft;
    Sprite* spWinOvBottomLeft;
    Sprite* spWinOvTopRight;
    Sprite* spWinOvBottomRight;
    Buffer* poCanvas;
    void (__cdecl *cb_win_caption)(GraphicWin*, char*, Buffer*);
    void (__cdecl *cb_win_redraw)();
};

struct ButtonGroup;

struct BaseButton : GraphicWin {
    int field_A14;
    int selected;
    Time time1;
    int repeat_delay;
    int repeat_interval;
    Time time2;
    int hovered;
    int button_id;
    char* name;
    char* bubbleText;
    int color;
    int bevel_upper;
    int bevel_lower;
    int bevel_thickness;
    int field_A94;
    int field_A98;
    int pressed;
    uint32_t min_click_duration;
    uint32_t press_time;
    ButtonGroup* group;
    int disabled;
    void (__cdecl *cb_left_click)(int);
    void (__cdecl *cb_left_down)(int);
};

struct ButtonGroup {
    BaseButton* buttons[32];
    int button_count;
    int select_button_id;
    uint32_t flags;
    int group_id;
    int skip_callback;
};

struct PushButton : BaseButton {
    Sprite* spUpLeftEdge;
    Sprite* spUpRightEdge;
    Sprite* spUpTopEdge;
    Sprite* spUpBottomEdge;
    Sprite* spUpTopLeftCorner;
    Sprite* spUpTopRightCorner;
    Sprite* spUpBottomLeftCorner;
    Sprite* spUpBottomRightCorner;
    Sprite* spUpCenter;
    Sprite* spDownLeftEdge;
    Sprite* spDownRightEdge;
    Sprite* spDownTopEdge;
    Sprite* spDownBottomEdge;
    Sprite* spDownTopLeftCorner;
    Sprite* spDownTopRightCorner;
    Sprite* spDownBottomLeftCorner;
    Sprite* spDownBottomRightCorner;
    Sprite* spDownCenter;
};

struct FlatButton : BaseButton {
    int override_state;
    int text_color[3];
    int sprite_vals[3];
    Sprite* spIconItem[3];
    Sprite* spLeftEdge[3];
    Sprite* spRightEdge[3];
    Sprite* spTopEdge[3];
    Sprite* spBottomEdge[3];
    Sprite* spTopLeftCorner[3];
    Sprite* spTopRightCorner[3];
    Sprite* spBottomLeftCorner[3];
    Sprite* spBottomRightCorner[3];
    Sprite* spCenter[3];
};

struct ImageButton : BaseButton {
    Sprite* spImage;
};

struct CheckButton : GraphicWin {
    int checked;
    int initial_state;
    void (__cdecl *cb_click)(int);
    void (__cdecl *cb_double_click)(int);
    Sprite* spUnchecked;
    Sprite* spChecked;
};

struct Scroll : GraphicWin {
    int flags;
    int item_id;
    int border_color;
    int range_min;
    int range_max;
    int reversed;
    int position;
    int repeat_delay;
    int repeat_rate;
    int repeat_time;
    int drag_pos;
    int paging;
    int click_area;
    int field_A48;
    RECT rcThumb;
    int color;
    int bar_thickness;
    Buffer* buffer;
    int bevel_thickness;
    int bevel_upper;
    int bevel_lower;
    Sprite* spItemThumb;
    Sprite* spItemBack;
    Sprite* spItemLeft[3];
    Sprite* spItemUp[3];
    Sprite* spItemRight[3];
    Sprite* spItemDown[3];
    FlatButton flatbutton_left;
    FlatButton flatbutton_right;
    void (__cdecl *cb_scroll_wheel)(int, int);
    void (__cdecl *cb_scroll_move)(int, int);
};

struct StringBox : GraphicWin {
    int field_A14;
    int max_lines;
    int top_line;
    Scroll scroll;
    StringList* externalList;
    StringStruct strings;
};

struct EditBox : GraphicWin {
    char text[256];
    int max_length;
    int view_offset;
    int back_color;
    int select_back_color;
    int select_text_color;
    int border_light_color;
    int border_dark_color;
    int border_width;
    int text_margin;
    int key_state;
    int edit_flags;
    int select_start;
    int cursor_pos;
    int caret_visible;
    Time time;
};

struct Dialog {
    void* vtable;
    Heap heap;
    Heap* pHeap;
    int heap_size;
    int dialog_flags;
    POINT ptWindow;
    SIZE szWindow;
    int field_34;
    int field_38;
    int field_3C;
    int field_40;
    int field_44;
    int field_48;
    int field_4C;
    int field_50;
    int field_54;
    int field_58;
    int field_5C;
    int field_60;
    int field_64;
    int field_68;
    int field_6C;
    Font* font1;
    Font* font2;
    Font* font3;
    int textColor1A;
    int textColor2A;
    int textColor3A;
    int textColor1B;
    int textColor2B;
    int textColor3B;
    int textColor1C;
    int textColor2C;
    int textColor3C;
    int textColor1D;
    int textColor2D;
    int textColor3D;
    int field_AC;
    int field_B0;
    int field_B4;
    int field_B8;
    StringStruct strings;
    int selected_pos;
    int field_F0;
};

struct ListBoxAlt {
    void* vtable;
    int list_dirty;
    int force_update;
    int scroll_flags;
    int select_text_color;
    int select_back_color;
    int top_index;
    int visible_item_count;
    int item_count;
    int border_light_color;
    int border_dark_color;
    int border_width;
    void (__cdecl *cb_draw_item)(int, int, uint32_t, int, int, int);
    int (__cdecl *cb_custom_draw)(int, int, int, int32_t*, int);
    int (__cdecl *cb_item_rect)(int, int, int, int32_t*);
    void (__cdecl *cb_select_item)(int);
    int field_40;
};

struct ListBox : ListBoxAlt {
    int field_44;
    GraphicWin graphicWin;
    int field_A5C;
    Dialog dialog;
};

struct RadioButtonAlt {
    void* vtable;
    Sprite* sprite1;
    Sprite* sprite2;
    int field_C;
    int field_10;
};

struct RadioButton : RadioButtonAlt {
    int field_14;
    GraphicWin graphicWin;
    int field_A2C;
    Dialog dialog;
};

struct CheckBoxAlt {
    void* vtable;
    int field_4;
    int field_8;
    int field_C;
    Sprite* sprite1;
    Sprite* sprite2;
};

struct CheckBox : CheckBoxAlt {
    int field_18;
    GraphicWin graphicWin;
    int field_A30;
    Dialog dialog;
};

struct SpriteBoxAlt {
    void* vtable;
    int show_selection;
    int selection_color;
    int field_C;
    Spot spot;
    int scale_numerator;
    int scale_denominator;
    StringStruct strings;
    int item_icon_width;
    int item_icon_height;
    int item_text_width;
    int item_line_height;
    void (__cdecl *cb_custom_draw)(int, int, int, int, int);
    int field_68;
    int field_6C;
    int field_70;
    int field_74;
    int field_78;
    int field_7C;
    int field_80;
    int field_84;
};

struct SpriteBox : SpriteBoxAlt {
    int field_88;
    GraphicWin graphicWin;
    int field_AA0;
    Dialog dialog;
};

struct EditGroupAlt {
    void* vtable;
    EditBox* editboxes[10];
    char* labels[10];
    int max_lengths[10];
    int max_value_width;
    int max_label_width;
    int field_84;
};

struct EditGroup : EditGroupAlt {
    int field_88;
    GraphicWin graphicWin;
    int field_AA0;
    Dialog dialog;
};

struct Dialogs {
    ListBoxAlt listBox;
    RadioButtonAlt radioButton;
    CheckBoxAlt checkBox;
    SpriteBoxAlt spriteBox;
    EditGroupAlt editGroup;
    int dialog_type;
    int field_184;
    GraphicWin graphicWin;
    int field_B9C;
    Dialog dialog;
};

struct BasePop : GraphicWin {
    GraphicWin* externalWindow;
    int externalLocA;
    int externalLocB;
    int externalWidth;
    int externalHeight;
    Heap heap;
    GraphicWin* drawWindow;
    int result_id;
    int active_id;
    char* captionText;
    int field_A4C;
    int field_A50;
    int field_A54;
    int field_A58;
    FlatButton flatButton1;
    FlatButton flatButton2;
    int button_count;
    int field_20F8;
    int field_20FC;
    int field_2100;
    int field_2104;
    int field_2108;
    int field_210C;
    int field_2110;
    int field_2114;
    Sprite sprite;
    Sprite* sprite_icon;
    Sprite* sprite_back;
    Sprite* sprite_logo;
    StringStruct buttonList;
    StringStruct textList;
    POINT ptPaddingDefault;
    POINT ptButtonGapDefault;
    POINT ptBorderDefault;
    int icon_area_width;
    int highlight_id;
    Dialogs dialogs;
    FileData waveFiles[2];
    int field_3094;
    Spot spot;
    int field_30A4;
    uint32_t popup_flags;
    int popup_extra;
    int total_button_count;
    POINT ptWindow;
    SIZE szWindow;
    int field_30C4;
    int field_30C8;
    int button_width;
    int button_height;
    int field_30D4;
    int field_30D8;
    int field_30DC;
    POINT ptBorder;
    POINT ptButtonGap;
    POINT ptPadding;
    int locA;
    int locB;
    int field_3100;
    int field_3104;
    int field_3108;
    int field_310C;
    Font* stringFont1;
    Font* stringFont2;
    Font* stringFont3;
    Font* stringFont4;
    int stringColor1A;
    int stringColor2A;
    int stringColor3A;
    int stringColorHyperA;
    int stringColor1B;
    int stringColor2B;
    int stringColor3B;
    int stringColorHyperB;
    int stringColor1C;
    int stringColor2C;
    int stringColor3C;
    int stringColorHyperC;
    int stringColor1D;
    int stringColor2D;
    int stringColor3D;
    int stringColorHyperD;
    int field_3160;
    int field_3164;
    int field_3168;
    Font* buttonFont1;
    Font* buttonFont2;
    Font* buttonFont3;
    uint8_t buttonColor1A;
    uint8_t buttonColor2A;
    uint8_t buttonColor3A;
    uint8_t field_317B;
    uint32_t buttonColor1B;
    uint32_t buttonColor2B;
    uint32_t buttonColor3B;
    uint32_t buttonColor1C;
    uint32_t buttonColor2C;
    uint32_t buttonColor3C;
    uint32_t buttonColor1D;
    uint32_t buttonColor2D;
    uint32_t buttonColor3D;
    uint8_t buttonFillColor;
    uint8_t field_31A1;
    uint8_t field_31A2;
    uint8_t field_31A3;
    int field_31A4;
    int field_31A8;
    int field_31AC;
    int field_31B0;
    int field_31B4;
    int soundParams[9][3];
    char* okText;
    char* cancelText;
    int field_322C;
};

struct Popup : BasePop {
    Scroll scroll;
};

struct NetMessage : Popup {
    Time time;
};

struct MenuItem {
    int menu_id;
    char* name;
    int item_flags;
    char* name_underline;
    PullDown* pulldown;
};

struct Menu : GraphicWin {
    void (__cdecl *cb_menu)(int menu_id);
    int item_count;
    int field_A1C;
    int field_A20;
    int current_id;
    int menu_flags;
    Spot spot;
    MenuItem menuitems[15];
};

struct PullDownItem {
    char* name;
    char* text_right;
    int item_id;
    int item_flags;
    char* name_underline;
};

struct PullDown : GraphicWin {
    int field_A14;
    PullDownItem pullitems[64];
    int field_F18;
    int field_F1C;
    int item_count;
    int max_item_width;
    int current_id;
    int visible_count;
    Menu* owner_menu;
    int pull_flags;
    void (__cdecl *cb_pull_draw_item)(GraphicWin*, int, RECT*);
    void (__cdecl *cb_pull_draw_back)(GraphicWin*);
};

struct AlphaMenu : Menu {
    Buffer buffer;
    Sprite sprites[4];
};

typedef AlphaMenu MainMenu;

struct PopMenu : Popup {
    PullDown pulldown;
};

struct SubInterface {
    void* vtable;
    int iface_mode;
};

struct MapWindow {
    void* vtable;
    void* rendercache;
    int field_8;
    TextureStore oUnknown[201];
    int RenderScale;
    int DrawFlags;
    int DrawToggleA;
    int DrawToggleB;
    int field_1DD7C;
    int field_1DD80;
    int field_1DD84;
    int field_1DD88;
    int EditorFlags;
    int LastEditTileX;
    int LastEditTileY;
    int ZoomFactor;
    int TileX;
    int TileY;
    int MapTileLeft;
    int MapTileTop;
    int MapPixelLeft;
    int MapPixelTop;
    int PixelsPerTileX;
    int PixelsPerHalfTileX;
    int PixelsPerTileY;
    int PixelsPerHalfTileY;
    int field_1DDC4;
    int field_1DDC8;
    int TileDistOddX;
    int TileDistOddY;
    int TileDistEvenX;
    int TileDistEvenY;
    int field_1DDDC;
    int field_1DDE0;
    int field_1DDE4;
    int field_1DDE8;
    int field_1DDEC;
    int field_1DDF0;
    int field_1DDF4;
    int field_1DDF8;
    int field_1DDFC;
    int field_1DE00;
    int field_1DE04;
    int field_1DE08;
    int field_1DE0C;
    int field_1DE10;
    int field_1DE14;
    int field_1DE18;
    int field_1DE1C;
    int field_1DE20;
    int field_1DE24;
    Buffer oCanvas1;
    Buffer oCanvas2;
    Buffer oCanvas3;
    int LastZoomFactor;
    int LastRenderScale;
    Font oFont1;
    int Font1Height;
    Font oFont2;
    int Font2Height;
    Font oFont3;
    int Font3Height;
    Sprite* pCursorSprite;
    int field_1EF50;
    ImageButton oImageBtns[4];
    int DrawOnlyCursor;
    RECT rcCursorClipA;
    RECT rcCursorClipB;
};

struct MapWinAlt : MapWindow {
    int field_21A68;
    GraphicWin oBufWin;
};

struct Console : MapWindow {
    GraphicWin oWinBuf;
    Buffer oCanvas4;
    Time oTimer;
    AlphaMenu oMainMenu;
    int field_23BC8;
    int field_23BCC;
    int field_23BD0;
    int cOwner;
    int InVehMode;
    int VehID;
    int ReadyVehID;
    int field_23BE4;
    int field_23BE8;
    int field_23BEC;
    int field_23BF0;
    int field_23BF4;
    int field_23BF8;
    int field_23BFC;
    int MapNeedsRedraw;
    int field_23C04;
    int CursorListIndex;
    int CursorListPrev;
    int CursorListX[32];
    int CursorListY[32];
    int CursorType;
    int CursorRange;
    int field_23D18;
    int field_23D1C;
    int field_23D20;
    int field_23D24;
    Sprite oSprite3;
    Sprite oSprite4;
    int field_23D80;
    int field_23D84;
    int field_23D88;
    int field_23D8C;
    int field_23D90;
    GraphicWin oMainWin;
};

struct PlanWindow : MapWindow {
    int is_active;
    int blink_phase;
    Buffer buffer;
    int line_count;
    int line_color[4];
    int line_value[4][4];
    int field_2204C;
    GraphicWin graphicWin;
};

struct ProdPicker : GraphicWin {
    int field_A14;
    Sprite sprite1;
    Sprite sprite2;
    Sprite sprite3;
    Font font1;
    Font font2;
    Font font3;
    Font font4;
    Time time;
    int field_B64;
    int field_B68;
    int field_B6C;
    int field_B70;
    FlatButton flatButton1;
    FlatButton flatButton2;
    FlatButton flatButton3;
    FlatButton flatButton4;
    FlatButton flatButton5;
    FlatButton flatButton6;
    FlatButton flatButton7;
    FlatButton flatButton8;
    FlatButton flatButton9;
    Scroll scroll;
    Caviar caviar;
    int field_A63C[64];
    CavVecFlt field_A73C;
    CavMatFlt field_A748;
    int faction_id;
    BASE* cur_base;
    int selected;
    int field_A778;
    int first_item;
    StringStruct strings1;
    StringStruct strings2;
    StringStruct strings3;
    int columns;
    int rows_visible;
    int item_count;
    int item_width;
    int item_height;
    int width;
    int height;
    int items_per_page;
    int field_A830;
    int field_A834;
    int field_A838;
    int field_A83C;
};

struct BaseWindow : GraphicWin {
    SubInterface subIFace;
    ProdPicker prodPicker;
    GraphicWin graphicWin2;
    Sprite sprites1[2];
    Sprite sprites2[2];
    Sprite sprites3[2];
    Sprite sprite4;
    Sprite sprite5;
    Sprite sprite6;
    Sprite sprites7[3];
    FlatButton flatButton1;
    Sprite sprites8[42];
    Sprite sprite9;
    Sprite sprite10;
    Sprite sprite11;
    Sprite sprite12;
    Sprite sprite13;
    Sprite sprite14;
    Sprite sprite15;
    Buffer buffer1;
    FlatButton flatButtons2[22];
    int field_1D048[64];
    Time time;
    Caviar caviar;
    int field_1E540[77];
    MapWinAlt oRender;
    int field_40AF4;
    int field_40AF8;
    int res_window_tab;
    int hover_tile_id;
    int hover_tile_state;
    int field_40B08;
    int cur_base_id;
    int facility_scroll_pos;
    int support_scroll_pos;
    int field_40B18;
    int field_40B1C;
    int support_overflow_flag;
    int field_40B24;
    int zoom_active;
    int queue_count;
    int field_40B30;
    int last_production_id;
    int hurry_mineral_cost;
    int field_40B3C;
    int field_40B40;
    int farm_drag_anchor_x;
    int farm_drag_anchor_y;
    int farm_drag_active;
    int field_40B50;
    int hover_changed_flag;
    int field_40B58;
    RECT rcSupport1;
    RECT rcSupport2;
    RECT rcSupportTab;
    RECT rcResWindow;
    RECT rcFacility1;
    RECT rcFacility2;
    RECT rcFacility3;
    RECT rcCommerce1;
    RECT rcCommerceLabel;
    RECT rcGovernor;
    RECT rcNutrient1;
    RECT rcNutrient2;
    RECT rcNutrient3;
    RECT rcGarrison;
    RECT rcEnergyAlloc;
    RECT rcExpenses;
    RECT rcPop;
    RECT rcProduction;
    RECT rcQueueTitle;
    RECT rcQueueList;
    RECT rcQueuePanel;
    RECT rcBaseName;
    RECT rcIneffic;
    int field_40CCC;
    int field_40CD0;
    int field_40CD4;
    int field_40CD8;
    RECT rcTutSupport;
    int field_40CEC;
    int field_40CF0;
    int field_40CF4;
    int field_40CF8;
    int field_40CFC;
    int field_40D00;
    int field_40D04;
    int field_40D08;
    int field_40D0C;
    int field_40D10;
    int field_40D14;
    int field_40D18;
    RECT rcMiscInfo;
    RECT rcFlatButton1;
    RECT rcFlatButton2;
    RECT rcFlatButton3;
    RECT rcFlatButton4;
    RECT rcFlatButton5;
    RECT rcFlatButton6;
    RECT rcFlatButton7;
    RECT rcFlatButton8;
    RECT rcFlatButton9;
    RECT rcFlatButton10;
    RECT rcFlatButton11;
    RECT rcFlatButton12;
    RECT rcFlatButton13;
    RECT rcFlatButton14;
    int field_40E0C;
    int field_40E10;
    int field_40E14;
    int field_40E18;
    int field_40E1C;
    int field_40E20;
    int field_40E24;
    int field_40E28;
    RECT rcFlatButton17;
    RECT rcFlatButton18;
    RECT rcFlatButton19;
    RECT rcFlatButton20;
    RECT rcFlatButton21;
    RECT rcFlatButton22;
    Font font1;
    Spot spot1;
    Spot spot2;
    Buffer buffer2;
    Scroll scroll1;
    Scroll scroll2;
    Scroll scroll3;
};

struct BattleWindow : SubInterface {
    Time time;
    RECT attack_panel;
    RECT defend_panel;
    RECT attack_label;
    RECT defend_label;
    RECT label_area;
    RECT unk_rect;
    RECT box_area;
};

struct CouncWindow : GraphicWin {
    SubInterface subIFace;
    int proposal_type;
    int candidate_faction_id;
    int proposal_outcome;
    int prev_gov_faction_id;
    int field_A2C;
    int field_A30;
    int field_A34;
    int vote_start_time;
    int vote_timeout;
    int selection_changed;
    int vote_faction_mask;
    Spot spot;
    int faction_vote[8];
    int faction_vote_count[8];
    int field_A94[8];
    Font font1;
    Font font2;
    Font font3;
    Font font4;
    Font font5;
    Font font6;
    RECT rcOutcomeText;
    RECT rcContentPanel;
    RECT rcTitleBar;
    RECT rcLeaderSeat[8][2];
    RECT rcVoteCount[3];
    RECT rcContentHeader;
    Sprite* sprite_leader[8][2];
    Sprite* sprite_faction[8][2];
    FlatButton flatButton1;
    FlatButton flatButton2;
    FlatButton flatButton3;
    FlatButton flatButton4;
    FlatButton flatButton5;
    FlatButton flatButton6;
};

struct Credits : GraphicWin {
    int scroll_offset;
    int line_count;
    char* lines[512];
    int field_121C;
    int field_1220;
    int field_1224;
    int field_1228;
    int line_height;
    int max_line_width;
    GraphicWin graphicWin2;
    Font font;
    Buffer buffer;
    FlatButton flatButton;
    Time time;
};

struct DatalinkWindow : GraphicWin {
    SubInterface subIFace;
    int field_A1C;
    int field_A20;
    Flic flic;
    int field_1508;
    Caviar caviar;
    int field_28DC[64];
    int category_id;
    int current_id;
    int current_history[20];
    int history_count;
    int list_updating;
    FlatButton flatButton1;
    FlatButton flatButton2;
    FlatButton flatButton3;
    FlatButton flatButton4;
    FlatButton flatButton5;
    FlatButton flatButton6;
    FlatButton flatButton7;
    FlatButton flatButton8;
    FlatButton flatButton9;
    FlatButton flatButton10;
    FlatButton flatButton11;
    FlatButton flatButton12;
    FlatButton flatButton13;
    FlatButton flatButton14;
    FlatButton flatButton15;
    FlatButton flatButton16;
    FlatButton flatButton17;
    FlatButton flatButton18;
    ButtonGroup buttonGroup;
    ListBox listBox;
    Font font1;
    Font font2;
    Font font3;
    Font font4;
    Font font5;
    Font font6;
    Font font7;
    Font font8;
    Font font9;
    Font font10;
    Font font11;
    RECT rcStringBox;
    int field_10344[4];
    RECT rcIcon;
    RECT rcTitle;
    RECT rcClient;
    RECT rcStats;
    RECT rcHelp;
    RECT rcContentClip;
    RECT rcContentFrame;
    RECT rcWindow;
    RECT rcCategoryHeader;
    RECT rcCategoryList;
    RECT rcFlatButton[18];
    StringBox stringBox1;
    StringBox stringBox2;
    StringBox stringBox3;
    StringBox stringBox4;
};

struct DesignWindow : GraphicWin {
    SubInterface subIFace;
    int field_A1C;
    int field_A20;
    int field_A24;
    int field_A28;
    int field_A2C;
    int field_A30;
    int field_A34;
    int field_A38;
    int field_A3C;
    int field_A40;
    int field_A44;
    int field_A48;
    RECT rcInfo;
    int field_A5C;
    int field_A60;
    int field_A64;
    int field_A68;
    RECT rcTitle;
    RECT rcAbilityGrid;
    RECT rcBackdrop;
    RECT rcVehicle;
    RECT rcChassis;
    RECT rcWeapon;
    RECT rcArmor;
    RECT rcReactor;
    RECT rcSpecial1;
    RECT rcSpecial2;
    RECT rcStack;
    RECT rcFlash;
    RECT rcCostText;
    RECT rcAbilityText;
    RECT rcButton1;
    RECT rcButton2;
    RECT rcButton3;
    RECT rcButton4;
    RECT rcButton5;
    RECT rcButton6;
    RECT rcButton7;
    RECT rcButton8;
    RECT rcButton9;
    int field_BDC;
    int field_BE0;
    int field_BE4;
    int field_BE8;
    int field_BEC;
    int field_BF0;
    int field_BF4;
    int field_BF8;
    int field_BFC;
    int field_C00;
    int field_C04;
    int field_C08;
    int field_C0C;
    int field_C10;
    int field_C14;
    int field_C18;
    int field_C1C;
    int field_C20;
    int field_C24;
    int field_C28;
    int field_C2C;
    int field_C30;
    int field_C34;
    int field_C38;
    int field_C3C;
    int field_C40;
    int field_C44;
    int field_C48;
    int field_C4C;
    int field_C50;
    int field_C54;
    int field_C58;
    int field_C5C;
    int field_C60;
    int field_C64;
    int field_C68;
    int field_C6C;
    int field_C70;
    int field_C74;
    int field_C78;
    int field_C7C;
    int field_C80;
    int field_C84;
    int field_C88;
    int field_C8C;
    int field_C90;
    int field_C94;
    int field_C98;
    int field_C9C;
    int field_CA0;
    int field_CA4;
    int field_CA8;
    int field_CAC;
    int field_CB0;
    int field_CB4;
    int field_CB8;
    RECT rcButton24;
    RECT rcButton25;
    int dialog_result;
    int highlight_unit_id;
    int stack_scroll_index;
    int blink_counter;
    FlatButton flatButtons[25];
    Spot spot1;
    Spot spot2;
    float rotate_angle;
    Time time;
    Caviar caviar;
    int field_13B6C[64];
    Buffer buffer;
    int faction_id;
    int unit_id;
    int unit_chassis_type;
    int unit_weapon_type;
    int unit_armor_type;
    int unit_ability_flags;
    int unit_reactor_type;
    int field_14210;
    int mineral_cost_factor;
    int unit_ability_id1;
    int unit_ability_id2;
    char custom_name[32];
    int field_14240;
    int field_14244;
    int field_14248;
    int field_1424C;
    int field_14250;
    int field_14254;
    int field_14258;
    int field_1425C;
    int field_14260;
    int field_14264;
    int field_14268;
    int field_1426C;
    char label_text[16][45];
    Font font1;
    Font font2;
    Font font3;
};

struct DiploPopup : GraphicWin {
    SubInterface subIFace;
    Font font1;
    Font font2;
    Font font3;
    int field_A94;
    Time time1;
    Time time2;
    Flic flic1;
    Flic flic2;
    int tick_count;
    Sprite* spDatalink;
    Sprite* spScanIcon;
    Sprite* spDiploLogo;
    Sprite* spDiploLand;
    RECT rcScanLabel;
    RECT rcScanIcon;
    RECT rcLeaderInfo;
    RECT rcFactionInfo;
    RECT field_2104;
    RECT rcHomeBase;
    RECT rcButton[3];
    int is_closed;
    FlatButton flatButtons[3];
};

struct DiploWindow : GraphicWin {
    SubInterface subIFace;
    int offer_count[2];
    int deal_status[2];
    int offer_type[2][8];
    int offer_value[2][8];
    int field_AAC;
    int field_AB0;
    int who_faction_id;
    int whom_faction_id;
    int field_ABC[261];
    Spot spot;
    RECT rcWindow;
    RECT rcSidePanelHeader;
    RECT rcSidePanelContent;
    RECT rcSidePanelHeader2;
    RECT rcSidePanelContent2;
    RECT rcChatInput;
    RECT rcChat;
    RECT rcTreatyStatus;
    RECT rcWhoPortrait;
    RECT rcWhomPortrait;
    RECT rcWhoName;
    RECT rcWhomName;
    RECT rcTradeLabel;
    RECT rcTradeGroup;
    RECT rcDiplomacyLabel;
    RECT rcDiplomacyGroup;
    RECT rcButton[13];
    FlatButton flatButtons[13];
    StringBox stringBox;
    ListBox listBox;
    EditBox editBox;
};

struct FameWindow : GraphicWin {
    int field_A14;
    int field_A18;
    int field_A1C;
    int field_A20;
    RECT rcContent;
    RECT field_A34;
    int line_height;
    int is_framed_mode;
    int faction_id;
    Spot spot;
    FlatButton flatButtons1[7];
    ButtonGroup buttonGroup;
    FlatButton flatButtons2[6];
    FlatButton flatButton3;
    int current_entry;
    Buffer buffer1;
    Buffer buffer2;
    RECT rcEntry;
    RECT rcImage;
    RECT rcDetails;
    RECT rcFactionButtons;
    RECT rcRecordButtons;
    RECT rcLandscape;
    Sprite sprites[12];
};

struct InfoWindow {
    RECT rcBounds;
    RECT rcLeftPanel;
    RECT rcRightPanel;
    Time time;
    Font font;
    int current_panel;
    int field_84;
    int state[2];
    int override_state;
    int blink_toggle;
    int field_98;
    int field_9C;
    int field_A0;
    int field_A4;
    int hold_flag;
    int skip_timer_proc;
    int field_B0;
    int field_B4;
    char line_text[2][12][80];
    int line_x[2][12];
    int line_y[2][12];
    int line_color1[2][12];
    int line_color2[2][12];
    int line_count[2];
    uint32_t text_length[2];
    uint32_t tick_count[2];
    PushButton pushbutton;
};

struct Interlude : GraphicWin {
    RECT rcText;
    StringList strings;
    Buffer buffer;
};

struct MainInterface : GraphicWin {
    SubInterface subIFace;
    RECT rcScreen;
    RECT rcScrollUp;
    RECT rcScrollDown;
    RECT rcScrollThumb;
    RECT rcLeftBtn;
    RECT rcRightBtn;
    RECT rcTurnFlic;
    int field_A8C[4];
    int field_A9C[4];
    RECT rcBaseLeft;
    RECT rcBaseRight;
    RECT rcBaseCenter;
    RECT rcActionBtns[25];
    RECT rcHiresBtns[6];
    RECT rcLeftPanelTop;
    RECT rcLeftPanel;
    RECT rcBaseArea;
    RECT rcTurnIcon;
    RECT rcSensor;
    RECT rcCenterInner;
    RECT rcDate;
    int field_D3C;
    int field_D40;
    int field_D44;
    int field_D48;
    RECT rcActionBound;
    RECT rcHiresBound;
    RECT rcAllButtons;
    int panel_height;
    RECT rcLeftPanelFixed;
    RECT rcRightPanel;
    RECT rcCenterTop;
    RECT rcCenterBottom;
    RECT rcButtonArea;
    RECT rcStatusArea;
    RECT rcAlertLeft;
    RECT rcAlertRight;
    FlatButton flatButton[42];
    ButtonGroup buttonGroup[4];
    int field_1EAC8;
    StringBox stringBox;
    Font font1;
    Font font2;
    Font font3;
    int field_216E4;
    int field_216E8;
    int field_216EC;
    int alert_count;
    Sprite sprites1[4];
    Sprite sprites2[4];
    Sprite sprites3[2];
    Sprite sprites4[2];
    Sprite sprites5[10];
    Sprite sprites6[10];
    Sprite sprites7[6];
    Sprite sprites8[3];
    Sprite sprites9[75];
    Sprite sprites10[18];
    Sprite sprite11;
    Sprite sprites12[6];
    Sprite sprites13[2];
    Flic flics1[2];
    Flic flic2;
    Spot spot;
    Time time1;
    Time time2;
};

struct MessageWindow {
    Sprite sprite;
    int field_2C;
    int field_30;
    int field_34;
    int field_38;
    Font font;
    ListBox listBox;
    StringBox stringBox;
};

struct MonuWindow : GraphicWin {
    int field_A14;
    int field_A18;
    int scene_width;
    int scene_height;
    int content_x1;
    int content_y1;
    int content_x2;
    int content_y2;
    RECT rcLayout;
    int line_height;
    int is_high_res;
    int is_detail_open;
    int faction_id;
    int current_type;
    FlatButton flatButton1;
    FlatButton flatButton2;
    Spot spot;
    Buffer buffer1;
    Buffer buffer2;
    Sprite sprites1[15];
    Sprite sprites2[15];
    RECT rcPreviewIcon;
    RECT rcTitleTextClip;
    RECT rcPortraitImage;
    RECT rcTypeSpot[14];
    Sprite sprites3[6];
    RECT rcRewardSlot[6];
    Sprite sprites4[7];
    Sprite sprites5[7];
    Sprite sprite6;
    Sprite sprite7;
    RECT rcRewardTypeSpot[6];
    RECT rcCompletionBadge;
};

struct MultiWindow : GraphicWin {
    int field_A14;
    int field_A18;
    int field_A1C;
    int field_A20;
    int is_visible;
    int field_A28;
    int field_A2C;
    int field_A30;
    int field_A34;
    RECT rcWindow;
    int field_A48;
    int field_A4C;
    int field_A50;
    Buffer buffer;
    Sprite sprites1[3];
    Sprite sprites2[3];
    Sprite sprite3;
    Sprite sprite4;
    Sprite sprite5;
    int active_faction_id;
    Sprite sprite6;
    Sprite sprite7;
    FlatButton flatButton1;
    FlatButton flatButton2;
    Font font1;
    Font font2;
    Spot spot;
};

struct NetWindow : GraphicWin {
    RECT rcTitle;
    RECT rcSession;
    RECT rcSessionTitle;
    RECT rcSessionFrame;
    RECT rcPlayersTitle;
    RECT rcPlayersFrame;
    RECT rcName[7];
    RECT rcFaction[7];
    RECT rcDiff[7];
    RECT rcLock[7];
    RECT rcButton1;
    RECT rcButton2;
    RECT rcReady[7];
    RECT rcChat;
    RECT rcChatInput;
    RECT rcChatFrame;
    RECT rcRulesTitle;
    RECT rcRulesFrame;
    RECT rcRulesLeft;
    RECT rcRulesRight;
    Spot spot;
    StringBox stringBox;
    EditBox editBox;
    CheckBox checkBox;
    FlatButton flatButton1;
    FlatButton flatButton2;
    char world_size_names[32][128];
    int exec_result;
    int all_ready;
    int field_761C;
    int field_7620;
    char filepath[260];
    int field_7728;
    void* plr_data;
    void* plr_data_alt;
};

struct NewTechWindow : GraphicWin {
    RECT rcWindow;
    RECT rcBackground;
    RECT rcStatus;
    RECT rcTechInfo;
    RECT rcCategory[4];
    RECT rcCategoryLabel[4];
    RECT rcBlurb;
    RECT rcBlurbText;
    RECT rcPrimaryButton;
    RECT rcShortBlurbButton;
    RECT rcLongBlurbButton;
    int tech_id;
    int field_B28;
    FlatButton flatButtons[3];
    ButtonGroup buttonGroup;
    StringBox stringBoxes[4];
    StringBox stringBox2;
};

struct PickTech : GraphicWin {
    int item_width;
    int item_height;
    int item_gap;
    int faction_id;
    int num_cols;
    int num_rows;
    int tech_count;
    int field_A30;
    int field_A34;
    int select_index;
    int select_valid;
    int box_left;
    int text_bottom_y;
    int box_width;
    int title_line_height;
    int text_top_y;
    int title_drawn;
    int tech_ids[89];
    Font font1;
    Font font2;
    Font font3;
    Font font4;
};

struct PickWindow : GraphicWin {
    int sprite_x;
    int sprite_y;
    int sprite_w;
    int sprite_h;
    Popup popup;
    int pick_mode;
    int pick_button_id;
    int window_result;
    int context_option;
    int custom_faction_count;
    int list_select_id;
    char filenames[24][24];
    char factionnames[24][24];
    void (__cdecl *cb_pickwin)(int);
    RECT rcBorder;
    RECT rcPanel;
    RECT rcSpriteLeft;
    RECT rcSpriteMiddle;
    RECT rcSpriteRight;
    FlatButton flatButton1;
    FlatButton flatButton2;
    FlatButton flatButton3;
    Sprite sprites1[3];
    Sprite sprites2[3];
    Sprite sprites3[3];
    Sprite sprites4[3];
    Sprite sprite5;
    RECT field_86AC;
    ListBox listBox;
    RECT field_9210;
    RECT field_9220;
    RECT field_9230;
    RECT field_9240;
    RECT field_9250;
    RECT field_9260;
    FlatButton flatButton4;
    FlatButton flatButton5;
    FlatButton flatButton6;
    FlatButton flatButton7;
    FlatButton flatButton8;
    FlatButton flatButton9;
    RECT field_D638[7];
    FlatButton flatButton10;
    FlatButton flatButton11;
    FlatButton flatButton12;
    FlatButton flatButton13;
    FlatButton flatButton14;
    FlatButton flatButton15;
    FlatButton flatButton16;
    ButtonGroup buttonGroup;
};

struct PrefWindow : GraphicWin {
    int field_A14;
    int field_A18;
    int field_A1C;
    uint32_t prefsFinal;
    uint32_t morePrefsFinal;
    uint32_t warningsFinal;
    int field_A2C;
    uint32_t prefsBasicPending;
    uint32_t morePrefsBasicPending;
    uint32_t prefsAdvPending;
    uint32_t morePrefsAdvPending;
    uint32_t prefsAutoPending;
    uint32_t morePrefsAutoPending;
    uint32_t warningsPending;
    uint32_t prefsAVPending;
    uint32_t morePrefsAVPending;
    uint32_t prefsMapPending;
    uint32_t morePrefsMapPending;
    uint32_t field_A5C;
    FlatButton bscPrefButton;
    FlatButton advPrefButton;
    FlatButton warnPrefButton;
    FlatButton autoPrefButton;
    FlatButton audioVisPrefButton;
    FlatButton mapPrefButton;
    FlatButton gammaButton;
    CheckBox bscPrefCheckBox;
    CheckBox advPrefCheckBox;
    CheckBox autoPrefCheckBox;
    CheckBox audioVisPrefCheckBox;
    CheckBox warnPrefCheckBox;
    CheckBox warnContPrefCheckBox;
    CheckBox mapPrefCheckBox;
    Scroll volumeMainScroll;
    Scroll volumeVoiceScroll;
    Scroll volumeSFXScroll;
    Scroll volumeMusicScroll;
    Scroll scroll5;
    FlatButton volumeMainToggle;
    FlatButton volumeSFXToggle;
    FlatButton volumeVoiceToggle;
    FlatButton volumeMusicToggle;
    FlatButton flatButton12;
    FlatButton restoreDefaultButton;
    FlatButton cancelButton;
    FlatButton okButton;
    FlatButton moreButton;
    Font* font1;
    Font* font2;
    Font* font3;
    Font* font4;
    Font* font5;
    Font* font6;
    Font* font7;
};

struct RatingWindow : GraphicWin {
    int field_A14;
    int field_A18;
    int display_width;
    int display_height;
    RECT rcViewport;
    RECT rcDialog;
    RECT rcPortrait;
    RECT rcButton;
    RECT rcTitle;
    RECT rcIntro;
    RECT rcRating;
    RECT rcName;
    int font_line_height;
    int has_frame;
    FlatButton flatButton1;
    FlatButton flatButton2;
    int select_page_id;
    int max_leader_index;
    Spot spot;
    ListBox listBox;
    Buffer buffer1;
    Buffer buffer2;
};

struct ReplayWindow : GraphicWin {
    int field_A14;
    int current_turn;
    Buffer buffer1;
    Buffer buffer2;
    MapWinAlt oMapWin;
    int field_239AC[893];
    FlatButton flatButton;
    Time time;
};

struct ReportWindow : GraphicWin {
    RECT rect_draw;
    int text_height;
    int field_A28;
    int field_A2C;
    int field_A30;
    int field_A34;
    FlatButton flatButtons1[7];
    int field_594C;
    int field_5950;
    int field_5954;
    int field_5958;
    int field_595C;
    int field_5960;
    int field_5964;
    int field_5968;
    int field_596C;
    int field_5970;
    RECT rect_client;
    RECT rect_frame;
    Spot spot;
    int field_59A0;
    int field_59A4;
    int box_width;
    int current_id;
    int field_59B0;
    int field_59B4;
    int field_59B8;
    int field_59BC;
    int field_59C0;
    int field_59C4;
    int field_59C8;
    int field_59CC;
    int field_59D0;
    int field_59D4;
    int field_59D8;
    int field_59DC;
    int field_59E0;
    int field_59E4;
    int field_59E8;
    int field_59EC;
    int field_59F0;
    int field_59F4;
    int field_59F8;
    int field_59FC;
    int field_5A00;
    int field_5A04;
    int field_5A08;
    ListBox listBox;
    FlatButton flatButton2;
    FlatButton flatButton3;
    RECT field_7BF8;
    ButtonGroup buttonGroup1;
    FlatButton flatButton4;
    FlatButton flatButton5;
    FlatButton flatButton6;
    ButtonGroup buttonGroup2;
    FlatButton flatButton7;
    FlatButton flatButton8;
    FlatButton flatButton9;
    int has_scroll;
    int scroll_pos;
    int scroll_min;
    int scroll_max;
    int scroll_paging;
    Scroll scroll;
    RECT field_E258;
    int line_height;
    int field_E26C;
    int scroll_range_dirty;
    Time time_blink;
    int field_E29C;
    int flic_offset_x;
    int flic_offset_y;
    int flic_center_x;
    int flic_center_y;
    RECT rect_flic;
    Time time_flic;
    Time time_expl;
    RECT rect_expl;
    Buffer buffer_expl;
    Buffer buffer_flic;
    Flic flic;
};

struct ReportInfc : SubInterface {
    int view_mode;
    int content_x;
    int content_y;
    int content_width;
    int field_18;
    int field_1C;
    RECT rcClient;
    RECT rcPanel;
    RECT rcFrame;
    RECT rcHeader;
    int mode_tab_pos[7];
    int field_7C;
    FlatButton flatButtons1[7];
    Sprite sprites1[21];
    int field_5330;
    int field_5334;
    int field_5338;
    int field_533C;
    int field_5340;
    int field_5344;
    int field_5348;
    int field_534C;
    int field_5350;
    int field_5354;
    int field_5358;
    int field_535C;
    int field_5360;
    int field_5364;
    int field_5368;
    int field_536C;
    int field_5370;
    int field_5374;
    int field_5378;
    int field_537C;
    int field_5380;
    FlatButton flatButtons2[7];
    int field_A298;
    int field_A29C;
    int field_A2A0;
    int field_A2A4;
    int field_A2A8;
    int field_A2AC;
    int field_A2B0;
    int field_A2B4;
    int field_A2B8;
    int field_A2BC;
    int field_A2C0;
    int field_A2C4;
    int field_A2C8;
    int field_A2CC;
    ListBox listBox1;
    ListBox listBox2;
    ButtonGroup buttonGroup1;
    FlatButton flatButton3;
    FlatButton flatButton4;
    ButtonGroup buttonGroup2;
    FlatButton flatButton5;
    FlatButton flatButton6;
    FlatButton flatButton7;
    FlatButton flatButton8;
    FlatButton flatButton9;
    FlatButton flatButton10;
    FlatButton flatButton11;
    FlatButton flatButton12;
    FlatButton flatButton13;
    ButtonGroup buttonGroup3;
    FlatButton flatButtons14[7];
    ButtonGroup buttonGroup4;
    FlatButton flatButtons15[5];
    FlatButton flatButton16;
    FlatButton flatButton17;
    FlatButton flatButton18;
    Font* font1;
    Font* font2;
    Font* font3;
    Font* font4;
    Font* font5;
    Font* font6;
    Font* font7;
    Font* font8;
    Font* font9;
    Font* font10;
    Font* font11;
    Font* font12;
    Font* font13;
    Font* font14;
    Font* font15;
    Spot spot;
    RECT rcContent;
    int is_active;
    int mode_history[19];
    int faction_id;
    int tech_id;
    int is_expanded_view;
    int is_busy;
    int suppress_scroll;
    int scroll_dirty;
    int field_1E240;
    int sort_column;
    int blink_frame;
    int blink_x;
    int blink_y;
    int entrylist[512][4];
    Sprite blinkSprites[4];
};

struct SelectPartWin : GraphicWin {
    Scroll scroll;
    int first_visible_index;
    int items_per_page;
    int faction_id;
    int columns_per_row;
    int rows_per_page;
    int part_count;
    int field_2B78;
    int field_2B7C;
    int current_index;
    int part_type;
    int chassis_type;
    int weapon_type;
    int field_2B90;
    int field_2B94;
    int field_2B98;
    Caviar caviar;
    int field_3F6C[64];
    Buffer buffer;
    Font font1;
    Font font2;
    int field_4644;
    int select_valid;
};

struct SetupWin : GraphicWin {
    int screen_width;
    int screen_height;
    Buffer* preview_buffers[3];
    int preview_x[3];
    int preview_y[3];
    Win* pMenuWin;
    Buffer buffer;
    int item_count;
    int current_item;
    Spot spot;
    StringStruct strings;
    StringStruct* current_list;
    Popup* popup;
    int field_1018;
    int field_101C;
    int field_1020;
    int field_1024;
    int field_1028;
    int field_102C;
    int field_1030;
    int field_1034;
    int field_1038;
    int field_103C;
    int field_1040;
    int field_1044;
    int field_1048;
    int field_104C;
    int field_1050;
    int field_1054;
    int field_1058;
    int field_105C;
    int field_1060;
    int field_1064;
    int field_1068;
    int field_106C;
    int field_1070;
    int field_1074;
    int field_1078;
    int field_107C;
    int field_1080;
    int field_1084;
    int field_1088;
    int field_108C;
    int field_1090;
    int field_1094;
    int field_1098;
    int field_109C;
    int field_10A0;
    int field_10A4;
    int field_10A8;
    int field_10AC;
    int field_10B0;
    int field_10B4;
    int field_10B8;
    int field_10BC;
    int field_10C0;
    int field_10C4;
    int field_10C8;
    int field_10CC;
    int field_10D0;
    int field_10D4;
    int field_10D8;
    int field_10DC;
    int field_10E0;
    int field_10E4;
    int field_10E8;
    int field_10EC;
    int field_10F0;
    int field_10F4;
    int field_10F8;
    int field_10FC;
    int field_1100;
    int field_1104;
    int field_1108;
    int field_110C;
    int field_1110;
    int field_1114;
    Buffer buffer2;
};

struct SocialWindow : GraphicWin {
    SubInterface subIFace;
    int field_A1C;
    Spot spot;
    int mouseover_choice;
    int mouseover_button;
    int field_A34[176];
    int faction_id;
    CSocialCategory socCategory;
    CSocialEffect socEffect;
    CSocialEffect socEffectOrig;
    int net_income;
    int tech_turns;
    int field_D68;
    CheckButton energyLockButtons[3];
    int field_2BF0;
    int field_2BF4;
    int field_2BF8;
    int field_2BFC;
    int field_2C00;
    int field_2C04;
    int field_2C08;
    int field_2C0C;
    int field_2C10;
    int field_2C14;
    int field_2C18;
    int field_2C1C;
    int field_2C20;
    int effect_maximize;
    int is_resetting;
    int field_2C2C;
    int field_2C30;
    int field_2C34;
    int economy_alloc_orig;
    int psych_alloc_orig;
    int labs_alloc_orig;
    int economy_alloc_alt;
    int psych_alloc_alt;
    int labs_alloc_alt;
    int economy_alloc_pending;
    int psych_alloc_pending;
    int labs_alloc_pending;
    int field_2C5C;
    Sprite socModifierNums[5][2];
    Sprite effectIcons[10][9];
    Sprite energyAllocLock[2];
    Sprite energyAllocArrow[2][3];
    Buffer energyAllocSlider[3][2];
    FlatButton flatButtons[35];
    ButtonGroup socCategoryGroups[4];
    ButtonGroup presetGroup;
    Font font1;
    Font font2;
    Font font3;
    Font font4;
    Font font5;
    Font font6;
    Font font7;
    Font font8;
    Font font9;
    RECT rcEnergyLock[3];
    RECT rcEnergyArrow[6];
    RECT rcPresets;
    RECT rcPreset[10];
    RECT rcTooltipSocEng[4];
    RECT rcSocChoice[4][4];
    RECT rcTooltipEffects;
    RECT rcTooltipEconomy;
    RECT rcTooltipLabs;
    RECT rcTooltipPsych;
    RECT rcMouseover;
    RECT rcTooltipFactionPower;
    RECT rcCancelButton;
    RECT rcResetButton;
    RECT rcOkButton;
    RECT rcInfo;
};

struct StatusWindow {
    int field_0;
    int field_4;
    int field_8;
    int field_C;
    int field_10;
    int field_14;
    int field_18;
    int field_1C;
    int field_20;
    int field_24;
    int field_28;
    int field_2C;
    Caviar caviar;
    int field_1400[64];
    CavVecFlt field_1500;
    CavMatFlt field_150C;
    Font oFontNorm;
    Font oFontItal;
    Font oFontBold;
    int terrain_info_type;
    int font_size;
    int field_15B0;
    int tile_x;
    int tile_y;
    int cur_veh_id;
    int cur_base_id;
    int pending_veh_id;
    int pending_base_id;
    int active_veh_id;
    int active_base_id;
    int iface_state;
    int is_double_click;
    int has_veh_at_loc;
    Spot spot;
};

struct TutWindow : Popup {
    int tile_x;
    int tile_y;
    int screen_x1;
    int screen_y1;
    int arrow_x1;
    int arrow_y1;
    int screen_x2;
    int screen_y2;
    int arrow_x2;
    int arrow_y2;
    int arrow_active;
    int field_53A8;
    int field_53AC;
    int field_53B0;
    int field_53B4;
    int field_53B8;
    int field_53BC;
    int field_53C0;
    int field_53C4;
    int field_53C8;
    int field_53CC;
    int field_53D0;
    GraphicWin* arrowWin;
};

struct WorldWindow : GraphicWin {
    int field_A14;
    int field_A18;
    Buffer buffer1;
    Buffer buffer2;
    MapWinAlt oMapWin;
};

struct NetFifo {
    int field_0;
    int field_4;
    int field_8;
    int field_C;
};

struct VoiceTx {
    int field_0;
    int field_4;
    int field_8;
    int field_C;
    int field_10;
    int field_14;
    int field_18;
    int field_1C;
    int field_20;
    int field_24;
    int field_28;
    int field_2C;
    int field_30;
    int field_34;
    int field_38;
    int field_3C;
    int field_40;
    int field_44;
    int field_48;
    int field_4C;
    int field_50;
    int field_54;
};

struct Net {
    void* vtable;
    int field_4;
    int field_8;
    int field_C;
    int field_10;
    int field_14;
    int field_18;
    int field_1C;
    int field_20;
    int field_24;
    int field_28;
    int field_2C;
    int field_30;
    int field_34;
    int field_38;
    int field_3C;
    int field_40;
    int field_44;
    int field_48;
    int field_4C;
    int field_50;
    int field_54;
    VoiceTx voiceTx;
    int field_B0;
    int field_B4;
    int field_B8;
    int field_BC;
    int field_C0;
    int field_C4;
    int field_C8;
    int field_CC;
    int field_D0;
    int field_D4;
    int field_D8;
    int field_DC;
    int field_E0;
    int field_E4;
    NetFifo netFifo1;
    int field_F8;
    int field_FC;
    int field_100;
    int field_104;
    int field_108;
    NetFifo netFifo2;
    int field_11C;
    int field_120;
    int field_124;
    int field_128;
    int field_12C;
    NetFifo netFifo3;
    int field_140;
    int field_144;
    int field_148;
    int field_14C;
    int field_150;
    int field_154;
    int field_158;
    int field_15C;
    int field_160;
    int field_164;
    int field_168;
    int field_16C;
    int field_170;
    int field_174;
    int field_178;
    int field_17C;
    int field_180;
    int field_184;
    int field_188;
    int field_18C;
    int field_190;
    int field_194;
    int field_198;
    int field_19C;
    int field_1A0;
    int field_1A4;
    int field_1A8;
    int field_1AC;
    int field_1B0;
    int field_1B4;
    int field_1B8;
    int field_1BC;
    int field_1C0;
    int field_1C4;
    int field_1C8;
    int field_1CC;
    int field_1D0;
    int field_1D4;
    int field_1D8;
    int field_1DC;
    int field_1E0;
    int field_1E4;
    int field_1E8;
    int field_1EC;
    int field_1F0;
    int field_1F4;
    int field_1F8;
    int field_1FC;
    int field_200[64];
    int field_300[64];
    int field_400[64];
    int field_500[64];
    int field_600[64];
    int field_700[24];
};

struct AlphaNet : Net {
    int field_760;
    int field_764;
    int field_768;
    int plr_list[8][103];
    int field_144C;
    int field_1450;
    int field_1454;
    int field_1458;
    int field_145C;
    int field_1460;
    int field_1464;
    int field_1468;
    int field_146C;
    int field_1470;
    int field_1474;
    int field_1478;
    int field_147C;
    int field_1480;
    int field_1484;
    int field_1488;
    Heap heap;
};

struct NetDaemon : AlphaNet {
    Lock lockstate;
    DeletionList deletelist;
    int dword_93E8C0;
    int dword_93E8C4;
    int dword_93E8C8;
    int dword_93E8CC;
    int dword_93E8D0;
    int dword_93E8D4;
    int dword_93E8D8;
    int dword_93E8DC;
    int dword_93E8E0;
    int dword_93E8E4;
    int dword_93E8E8;
    int dword_93E8EC;
    int dword_93E8F0;
    int dword_93E8F4;
    int dword_93E8F8;
    int dword_93E8FC;
    int dword_93E900;
    int VehAttackFlags;
    int dword_93E908;
    int dword_93E90C;
    int dword_93E910[8];
    int dword_93E930;
    int dword_93E934;
    int dword_93E938;
    int dword_93E93C;
    int dword_93E940;
    int dword_93E944;
    int dword_93E948;
    int dword_93E94C;
    int dword_93E950;
    int dword_93E954;
    int dword_93E958;
    int dword_93E95C;
    int dword_93E960;
    int dword_93E964;
    int dword_93E968;
    int dword_93E96C;
    int dword_93E970;
    int dword_93E974;
};

struct MultiDebug : GraphicWin {
    Font font;
    int field_A3C;
    Time time;
};

#pragma pack(pop)

typedef MAP CTile;
typedef BASE CCity;
typedef Console CMain;
typedef GraphicWin CWinBuffed;
typedef Win CWinBase;
typedef Menu CMainMenu;
typedef Buffer CCanvas;
typedef Time CTimer;
typedef Font CFont;
typedef Sprite CSprite;
typedef Texture CImage;
typedef TextureStore CMainArrayItem;
typedef Spot CHitBoxList;
typedef SpotNode CHitBox;
typedef Heap CMemAllocator;
typedef Filemap CFile;
typedef Strings CLabelAllocator;
typedef Palette CPalette;

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Winvalid-offsetof"

static_assert(sizeof(StringStructData) == 0x18, "");
static_assert(sizeof(StringStructNode) == 0x1C, "");
static_assert(sizeof(StringStruct) == 0x30, "");
static_assert(sizeof(Heap) == 0x14, "");
static_assert(sizeof(SpotNode) == 0x18, "");
static_assert(sizeof(Spot) == 0xC, "");
static_assert(sizeof(RenderCache) == 0xC, "");
static_assert(sizeof(TextureStore) == 0x260, "");
static_assert(sizeof(SquareLock) == 0xC, "");
static_assert(sizeof(PlayerLock) == 0x1C, "");
static_assert(sizeof(Lock) == 0xEC, "");
static_assert(sizeof(DeletionList) == 0x5A4, "");
static_assert(sizeof(Time) == 0x28, "");
static_assert(sizeof(Font) == 0x28, "");
static_assert(sizeof(FontQueue) == 0xA0, "");
static_assert(sizeof(Sound) == 0x54, "");
static_assert(sizeof(Effect) == 0x6C, "");
static_assert(sizeof(Palette) == 0x454, "");
static_assert(sizeof(Caviar) == 0x13D0, "");
static_assert(sizeof(Buffer) == 0x588, "");
static_assert(sizeof(Sprite) == 0x2C, "");
static_assert(sizeof(Texture) == 0x70, "");
static_assert(sizeof(Flic) == 0xAE4, "");
static_assert(sizeof(Win) == 0x444, "");
static_assert(sizeof(GraphicWin) == 0xA14, "");
static_assert(sizeof(BaseButton) == 0xAB8, "");
static_assert(sizeof(PushButton) == 0xB00, "");
static_assert(sizeof(FlatButton) == 0xB4C, "");
static_assert(sizeof(ImageButton) == 0xABC, "");
static_assert(sizeof(CheckButton) == 0xA2C, "");
static_assert(sizeof(ButtonGroup) == 0x94, "");
static_assert(sizeof(Scroll) == 0x214C, "");
static_assert(sizeof(StringBox) == 0x2BA0, "");
static_assert(sizeof(EditBox) == 0xB74, "");
static_assert(sizeof(Dialog) == 0xF4, "");
static_assert(sizeof(ListBox) == 0xB54, "");
static_assert(sizeof(RadioButton) == 0xB24, "");
static_assert(sizeof(CheckBox) == 0xB28, "");
static_assert(sizeof(SpriteBox) == 0xB98, "");
static_assert(sizeof(EditGroup) == 0xB98, "");
static_assert(sizeof(Dialogs) == 0xC94, "");
static_assert(sizeof(BasePop) == 0x3230, "");
static_assert(sizeof(Popup) == 0x537C, "");
static_assert(sizeof(Menu) == 0xB64, "");
static_assert(sizeof(PullDown) == 0xF40, "");
static_assert(sizeof(AlphaMenu) == 0x119C, "");
static_assert(sizeof(MainMenu) == 0x119C, "");
static_assert(sizeof(PopMenu) == 0x62BC, "");
static_assert(sizeof(NetMessage) == 0x53A4, "");
static_assert(sizeof(SubInterface) == 0x8, "");
static_assert(sizeof(MapWindow) == 0x21A68, "");
static_assert(sizeof(MapWinAlt) == 0x22480, "");
static_assert(sizeof(Console) == 0x247A8, "");
static_assert(sizeof(PlanWindow) == 0x22A64, "");
static_assert(sizeof(ProdPicker) == 0xA840, "");
static_assert(sizeof(BaseWindow) == 0x47838, "");
static_assert(sizeof(BattleWindow) == 0xA0, "");
static_assert(sizeof(CouncWindow) == 0x515C, "");
static_assert(sizeof(Credits) == 0x2D6C, "");
static_assert(sizeof(DatalinkWindow) == 0x1B394, "");
static_assert(sizeof(DesignWindow) == 0x145B8, "");
static_assert(sizeof(DiploPopup) == 0x433C, "");
static_assert(sizeof(DiploWindow) == 0xE5F0, "");
static_assert(sizeof(FameWindow) == 0xB69C, "");
static_assert(sizeof(InfoWindow) == 0x14D0, "");
static_assert(sizeof(Interlude) == 0xFDC, "");
static_assert(sizeof(MainInterface) == 0x25090, "");
static_assert(sizeof(MessageWindow) == 0x3758, "");
static_assert(sizeof(MonuWindow) == 0x36DC, "");
static_assert(sizeof(MultiWindow) == 0x28B8, "");
static_assert(sizeof(NetWindow) == 0x7734, "");
static_assert(sizeof(NewTechWindow) == 0x107C4, "");
static_assert(sizeof(PickTech) == 0xC5C, "");
static_assert(sizeof(PickWindow) == 0x12650, "");
static_assert(sizeof(PrefWindow) == 0x1B3D0, "");
static_assert(sizeof(RatingWindow) == 0x37BC, "");
static_assert(sizeof(ReplayWindow) == 0x25314, "");
static_assert(sizeof(ReportWindow) == 0xF914, "");
static_assert(sizeof(ReportInfc) == 0x20304, "");
static_assert(sizeof(SelectPartWin) == 0x464C, "");
static_assert(sizeof(SetupWin) == 0x16A0, "");
static_assert(sizeof(SocialWindow) == 0x1F2F0, "");
static_assert(sizeof(StatusWindow) == 0x15EC, "");
static_assert(sizeof(TutWindow) == 0x53D8, "");
static_assert(sizeof(WorldWindow) == 0x239AC, "");
static_assert(sizeof(AlphaNet) == 0x14A0, "");
static_assert(sizeof(NetDaemon) == 0x1BE8, "");
static_assert(sizeof(MultiDebug) == 0xA68, "");
static_assert(offsetof(Caviar, object_item) == 0x10C, "");
static_assert(offsetof(Caviar, object_data) == 0x74C, "");
static_assert(offsetof(Dialogs, field_B9C) == 0xB9C, "");
static_assert(offsetof(BasePop, sprite_icon) == 0x2144, "");
static_assert(offsetof(BasePop, field_3100) == 0x3100, "");
static_assert(offsetof(Console, field_1DDE4) == 0x1DDE4, "");
static_assert(offsetof(Console, oWinBuf) == 0x21A68, "");
static_assert(offsetof(Console, field_23BC8) == 0x23BC8, "");
static_assert(offsetof(MapWindow, field_1DD7C) == 0x1DD7C, "");
static_assert(offsetof(MapWindow, field_1EF50) == 0x1EF50, "");
static_assert(offsetof(MapWinAlt, field_21A68) == 0x21A68, "");
static_assert(offsetof(BaseWindow, field_1D048) == 0x1D048, "");
static_assert(offsetof(BaseWindow, field_40AF4) == 0x40AF4, "");
static_assert(offsetof(BaseWindow, field_40CCC) == 0x40CCC, "");
static_assert(offsetof(DesignWindow, field_14240) == 0x14240, "");
static_assert(offsetof(MainInterface, field_1EAC8) == 0x1EAC8, "");
static_assert(offsetof(PlanWindow, field_2204C) == 0x2204C, "");
static_assert(offsetof(PickWindow, field_86AC) == 0x86AC, "");
static_assert(offsetof(PickWindow, field_D638) == 0xD638, "");
static_assert(offsetof(ReportWindow, field_594C) == 0x594C, "");
static_assert(offsetof(ReportWindow, field_E29C) == 0xE29C, "");
static_assert(offsetof(ReportInfc, field_5330) == 0x5330, "");
static_assert(offsetof(ReportInfc, field_A2B4) == 0xA2B4, "");
static_assert(offsetof(ReportInfc, field_1E240) == 0x1E240, "");
static_assert(offsetof(Net, field_154) == 0x154, "");
static_assert(offsetof(Net, field_700) == 0x700, "");
static_assert(offsetof(AlphaNet, field_144C) == 0x144C, "");

#pragma GCC diagnostic pop

