#pragma once

/* Temporarily disable warnings for thiscall parameter type. */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wattributes"

#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include <windows.h>
#include <set>
#include <map>
#include <list>
#include <string>
#include <vector>
#include <algorithm>
#include <unordered_map>

#ifdef __GNUC__
#pragma GCC poison strcat_s strcpy_s
#endif

typedef uint8_t byte;
typedef struct { char str[256]; } char256;

struct CChassis;
extern CChassis* Chassis;
struct CWeapon;
extern CWeapon* Weapon;
struct CArmor;
extern CArmor* Armor;
struct UNIT;
extern UNIT* Units;
struct VEH;
extern VEH* Vehicles;
struct Faction;
extern Faction* Factions;
struct MFaction;
extern MFaction* MFactions;
extern int* const GameState;
extern int* const GameRules;
extern const int MaxVehNum;
extern const int MaxProtoNum;
extern const int MaxPlayerNum;
extern const int MaxBaseSpecNum;
extern const int MaxProtoFactionNum;
bool is_human(int faction_id);
bool can_repair(int unit_id);
bool can_monolith(int unit_id);

#include "engine_enums.h"
#include "engine_types.h"
#include "engine_base.h"
#include "engine_veh.h"
#include "engine_win.h"

struct MapTile {
    int x;
    int y;
    int i;
    MAP* sq;
};

struct TileValue {
    int x;
    int y;
    int i;
    MAP* sq;
    int nutrient;
    int mineral;
    int energy;
};

struct Point {
    int x;
    int y;

    bool operator==(const Point& obj) const {
        return (x == obj.x && y == obj.y);
    }
    bool operator<(const Point& obj) const {
        return x < obj.x || (x == obj.x && y < obj.y);
    }
};

template <>
struct std::hash<Point> {
    std::size_t operator()(const Point& p) const {
        return p.x ^ (p.y << 16);
    }
};

struct MapNode {
    int x;
    int y;
    int type;

    bool operator<(const MapNode& obj) const {
        return x < obj.x || (x == obj.x && (
            y < obj.y || (y == obj.y && (type < obj.type))
        ));
    }
};

template <class T, class C>
bool has_item(const T& a, const C& b) {
    return std::find(a.begin(), a.end(), b) != a.end();
}

template <class T>
const T& min (const T& a, const T& b) {
    return std::min(a, b);
}

template <class T>
const T& max (const T& a, const T& b) {
    return std::max(a, b);
}

template <class T>
const T& clamp (const T& value, const T& low, const T& high) {
    return (value < low ? low : (value > high ? high : value));
}

inline VehAblFlag operator| (VehAblFlag a, VehAblFlag b) { return (VehAblFlag)((int)a | (int)b); }
inline VehAblFlag& operator|= (VehAblFlag& a, VehAblFlag b) { return (VehAblFlag&)((int&)a |= (int)b); }

struct WItem {
    int AI_growth;
    int AI_tech;
    int AI_wealth;
    int AI_power;
    int AI_fight;
};

struct PItem {
    int item_id;
    int explore;
    int discover;
    int build;
    int conquer;
    int energy;
};

struct PInfo {
    int former;
    int safety;
    int target;
    int roads;
    int shore;
    int unit_near;
    int unit_path;
    int enemy;
    int enemy_near;
    int enemy_dist;
    int overlay;

    int get_enemy_dist() const {
        return (enemy_dist > 0 ? enemy_dist : 20);
    }
};

typedef std::unordered_map<Point, PInfo> PMTable;
typedef std::set<MapNode> NodeSet;
typedef std::set<Point> Points;
typedef std::list<Point> PointList;
typedef std::set<std::string> set_str_t;
typedef std::vector<std::string> vec_str_t;
typedef std::map<std::string, std::string> map_str_t;

typedef int (__cdecl *fp_none)();
typedef int (__cdecl *fp_1int)(int);
typedef int (__cdecl *fp_2int)(int, int);
typedef int (__cdecl *fp_3int)(int, int, int);
typedef int (__cdecl *fp_4int)(int, int, int, int);
typedef int (__cdecl *fp_5int)(int, int, int, int, int);
typedef int (__cdecl *fp_6int)(int, int, int, int, int, int);
typedef int (__cdecl *fp_7int)(int, int, int, int, int, int, int);
typedef int (__cdecl *fp_8int)(int, int, int, int, int, int, int, int);

typedef int (__thiscall *tc_1int)(void*);
typedef int (__thiscall *tc_2int)(void*, int);
typedef int (__thiscall *tc_3int)(void*, int, int);
typedef int (__thiscall *tc_4int)(void*, int, int, int);
typedef int (__thiscall *tc_5int)(void*, int, int, int, int);
typedef int (__thiscall *tc_6int)(void*, int, int, int, int, int);
typedef int (__thiscall *tc_7int)(void*, int, int, int, int, int, int);
typedef int (__thiscall *tc_8int)(void*, int, int, int, int, int, int, int);

/*
pad_1 in MFaction is reserved for faction specific variables.
pad_2 in MFaction[0] is reserved for global game state.
*/
struct ThinkerData {
    uint64_t reserved;
    uint64_t game_time_spent;
    char build_date[12];
    uint32_t map_random_value;
    int8_t padding[144];
};

static_assert(sizeof(struct CTerraform) == 32, "");
static_assert(sizeof(struct CResourceInfo) == 144, "");
static_assert(sizeof(struct CCitizen) == 28, "");
static_assert(sizeof(struct CResourceName) == 8, "");
static_assert(sizeof(struct CCombatMode) == 16, "");
static_assert(sizeof(struct CBonusName) == 24, "");
static_assert(sizeof(struct CCombatMode) == 16, "");
static_assert(sizeof(struct CRules) == 308, "");
static_assert(sizeof(struct CEnergy) == 8, "");
static_assert(sizeof(struct CChassis) == 144, "");
static_assert(sizeof(struct CNatural) == 8, "");
static_assert(sizeof(struct CWeapon) == 16, "");
static_assert(sizeof(struct CSocialCategory) == 16, "");
static_assert(sizeof(struct CSocialEffect) == 44, "");
static_assert(sizeof(struct CSocialParam) == 104, "");
static_assert(sizeof(struct CSocialField) == 212, "");
static_assert(sizeof(struct CMight) == 8, "");
static_assert(sizeof(struct CTimeControl) == 32, "");
static_assert(sizeof(struct CArmor) == 16, "");
static_assert(sizeof(struct CTech) == 44, "");
static_assert(sizeof(struct CWorldbuilder) == 124, "");
static_assert(sizeof(struct CMorale) == 8, "");
static_assert(sizeof(struct CReactor) == 12, "");
static_assert(sizeof(struct COrder) == 12, "");
static_assert(sizeof(struct CFacility) == 48, "");
static_assert(sizeof(struct CProposal) == 12, "");
static_assert(sizeof(struct CAbility) == 28, "");
static_assert(sizeof(struct MFaction) == 1436, "");
static_assert(sizeof(struct Faction) == 8396, "");
static_assert(sizeof(struct BASE) == 308, "");
static_assert(sizeof(struct UNIT) == 52, "");
static_assert(sizeof(struct VEH) == 52, "");
static_assert(sizeof(struct MAP) == 44, "");
static_assert(sizeof(struct Monument) == 1268, "");
static_assert(sizeof(struct ReplayEvent) == 8, "");
static_assert(sizeof(struct ThinkerData) == 176, "");

/*
Thinker functions that are replacements to the SMACX binary versions
should be prefixed with 'mod_' if their equivalent is also listed here.
*/

extern const char** const EngineVersion;
extern const char** const EngineDate;
extern char* const LastSavePath;
extern char* const MapFilePath;
extern char* const StrBuffer;
extern BASE** const CurrentBase;
extern int* const CurrentBaseID;
extern int* const ComputeBaseID;
extern int* const BaseUpkeepDrawID;
extern int* const BaseReservedTiles;
extern int* const BaseFindDist;
extern int* const BaseGrowthRate;
extern int* const BaseUpkeepFlag;
extern int* const BaseUpkeepState;
extern int* const BasePsychTalents;
extern int* const BasePsychNDrones;
extern int* const BasePsychSDrones;
extern int* const BaseTileFlags;
extern int* const BaseResourceConvoyFrom;
extern int* const BaseResourceConvoyTo;
extern int* const BaseVehPacifismCount;
extern int* const BaseForcesSupported;
extern int* const BaseForcesMaintCost;
extern int* const BaseForcesMaintCount;
extern int* const BaseCommerceImport;
extern int* const BaseCommerceExport;
extern int* const BaseTerraformEnergy;
extern int* const BaseTerraformReduce;
extern int* const ReplayEventSize;
extern int* const ScnVictFacilityObj;
extern int* const SolarFlaresEvent;
extern int* const BaseCount;
extern int* const VehCount;
extern int* const GameLanguage;
extern int* const GamePreferences;
extern int* const GameMorePreferences;
extern int* const GameWarnings;
extern int* const GameState;
extern int* const GameRules;
extern int* const GameMoreRules;
extern int* const DiffLevel;
extern int* const ExpansionEnabled;
extern int* const MultiplayerActive;
extern int* const PbemActive;
extern int* const CurrentTurn;
extern int* const CurrentFaction;
extern int* const CurrentPlayerFaction;
extern int* const TechValidCount;
extern int* const TechCommerceCount;
extern int* const MapRandomSeed;
extern int* const MapToggleFlat;
extern int* const MapAreaTiles;
extern int* const MapAreaSqRoot;
extern int* const MapAreaX;
extern int* const MapAreaY;
extern int* const MapHalfX;
extern int* const MapSizePlanet;
extern int* const MapOceanCoverage;
extern int* const MapLandCoverage;
extern int* const MapErosiveForces;
extern int* const MapPlanetaryOrbit;
extern int* const MapCloudCover;
extern int* const MapNativeLifeForms;
extern int* const MapLandmarkCount;
extern int* const MapSeaLevel;
extern int* const MapSeaLevelCouncil;
extern int* const MapAbstractLongBounds;
extern int* const MapAbstractLatBounds;
extern int* const MapAbstractArea;
extern int* const MapBaseSubmergedCount;
extern int* const MapBaseIdClosestSubmergedVeh;
extern int* const BrushVal1;
extern int* const BrushVal2;
extern int* const WorldBuildVal1;
extern int* const AltNaturalDefault;
extern int* const AltNatural;
extern int* const ObjectiveReqVictory;
extern int* const ObjectivesSuddenDeathVictory;
extern int* const ObjectiveAchievePts;
extern int* const VictoryAchieveBonusPts;
extern int* const CurrentMissionYear;
extern int* const StartingMissionYear;
extern int* const EndingMissionYear;
extern int* const TectonicDetonationCount;
extern int* const ClimateValueA;
extern int* const ClimateValueB;
extern int* const ClimateValueC;
extern int* const ClimateFutureChange;
extern int* const SunspotDuration;
extern int* const MountPlanetX;
extern int* const MountPlanetY;
extern int* const DustCloudDuration;
extern int* const SunspotDuration;
extern int* const GovernorFaction;
extern int* const ProposalPassCount;
extern int* const gender_default;
extern int* const plurality_default;
extern int* const diplo_second_faction;
extern int* const diplo_third_faction;
extern int* const diplo_tech_faction;
extern int* const reportwin_opponent_faction;
extern int* const dword_93A958;
extern int* const diplo_value_93FA98;
extern int* const diplo_value_93FA24;
extern int* const diplo_entry_id;
extern int* const diplo_counter_proposal_id;
extern int* const diplo_current_proposal_id;
extern int* const diplo_ask_base_swap_id;
extern int* const diplo_bid_base_swap_id;
extern int* const diplo_tech_id1;
extern int* const diplo_tech_id2;
extern int* const VehAttackFlags;
extern int* const VehDrawAttackID;
extern int* const VehDrawDefendID;
extern int* const CurrentVehID;
extern int* const dword_6E8150;
extern int* const dword_7AD330;
extern int* const dword_74DA9C;
extern int* const dword_7FE06C;
extern int* const dword_8C6B3C;
extern int* const dword_90DB84;
extern int* const dword_90EA3C;
extern int* const dword_93A96C;
extern int* const dword_93A98C;
extern int* const dword_93E960;
extern int* const dword_9A6510;
extern int* const dword_9B206C;
extern int* const ScreenWidth;
extern int* const ScreenHeight;
extern char256* const ParseStrBuffer;
extern int* const ParseNumTable;
extern int* const ParseStrPlurality;
extern int* const ParseStrGender;
extern int* const DialogChoices;
extern int* const DialogToggle;
extern int* const GameHalted;
extern int* const ControlTurnA;
extern int* const ControlTurnB;
extern int* const ControlTurnC;
extern int* const ControlUpkeepA;
extern int* const ControlWaitLoop;
extern int* const SkipTechScreenA;
extern int* const SkipTechScreenB;
extern int* const NetUpkeepState;
extern int* const WorldAddTemperature;
extern int* const WorldSkipTerritory;
extern int* const GameDrawState;
extern int* const WinModalState;
extern int* const DiploWinState;
extern int* const PopupDialogState;
extern RECT* const RenderTileBounds;

extern int* const VehDropLiftVehID;
extern int* const VehLiftX;
extern int* const VehLiftY;
extern int* const VehBitError;
extern int* const VehBasicBattleMorale;
extern int* const VehBattleModCount;
extern int* const VehBattleState;
extern int (*const VehBattleModifier)[4];
extern char (*const VehBattleDisplay)[4][80];
extern char** const VehBattleDisplayTerrain;
extern int* const ProbeHasAlgoEnhancement;
extern int* const ProbeTargetFactionID;
extern int* const ProbeTargetHasHSA;

extern uint8_t* const TechOwners;
extern int* const SecretProjects;
extern int* const CostRatios;
extern uint8_t* const FactionStatus;
extern int16_t (*const FactionTurnMight)[8];
extern int* const FactionRankings;
extern int* const RankingFactionIDUnk1;
extern int* const RankingFactionIDUnk2;
extern int* const FactionRankingsUnk;
extern int* const DiploFriction;
extern int* const DiploFrictionFactionIDWith;
extern int* const DiploFrictionFactionID;

const int MaxVehModNum = 8192;
extern VEH ArrayVehs[MaxVehModNum+2];
extern VEH* const VehsMod;

extern ThinkerData* ThinkerVars;
extern MFaction* MFactions;
extern Faction* Factions;
extern BASE* Bases;
extern UNIT* Units;
extern VEH* const VehsDef;
extern VEH* Vehs;
extern MAP** MapTiles;
extern uint8_t** MapAbstract;
extern Continent* Continents;
extern Landmark* Landmarks;
extern Console* MapWin;
extern BaseWindow* BaseWin;
extern Win* BattleWin;
extern Win* CouncilWin;
extern Win* DatalinkWin;
extern Win* DesignWin;
extern Win* DiploWin;
extern Win* FameWin;
extern Win* InfoWin;
extern Win* MainWin;
extern FlatButton* FlatButtons;
extern Win* StringBox;
extern Win* DetailWin;
extern Win* BaseMapWin;
extern Win* MessageWin;
extern Win* MonuWin;
extern Win* MultiWin;
extern Win* NetWin;
extern Win* NetTechWin;
extern Win* PickWin;
extern Win* PlanWin;
extern Win* PrefWin;
extern Win* ReportWin;
extern Win* SocialWin;
extern Win* StatusWin;
extern Win* TutWin;
extern Win* WorldWin;
extern Font** MapLabelFont;
extern Sprite** FactionPortraits;
extern void* Sounds;
extern void* NetMsg;
extern AlphaNet* NetState;
extern Lock* LockState;
extern Path* Paths;
extern FileFindPath* FileFind;
extern void* TextTable;
extern Label* TextLabels;

extern CTerraform* Terraform;
extern CResourceInfo* ResInfo;
extern CCitizen* Citizen;
extern CResourceName* ResName;
extern CCombatMode* OffenseMode;
extern CBonusName* BonusName;
extern CSocialParam* SocialParam;
extern CCombatMode* DefenseMode;
extern CRules* Rules;
extern CEnergy* Energy;
extern CChassis* Chassis;
extern CNatural* Natural;
extern CWeapon* Weapon;
extern CSocialField* SocialField;
extern DefaultPref* DefaultPrefs;
extern AlphaIniPref* AlphaIniPrefs;
extern CMandate* Mandate;
extern CMight* Might;
extern CTimeControl* TimeControl;
extern CArmor* Armor;
extern CTech* Tech;
extern CWorldbuilder* WorldBuilder;
extern ReplayEvent* ReplayEvents;
extern CMorale* Morale;
extern CReactor* Reactor;
extern COrder* Order;
extern CFacility* Facility;
extern CProposal* Proposal;
extern CAbility* Ability;
extern char** Compass;
extern char** PlansShortName;
extern char** Repute;
extern char** Difficulty;
extern char** Mood;
extern char** TriadName;
extern char** PlansFullName;

typedef int(__cdecl *Fbattle_fight_1)(int veh_id, int offset, int table_offset, int option, int* def_id);
typedef int(__cdecl *Fbattle_fight_2)(int veh_id, int offset, int tx, int ty, int table_offset, int option, int* def_id);
typedef int(__cdecl *Fpropose_proto)(int faction_id, VehChassis chassis, VehWeapon weapon, VehArmor armor,
    int abilities, VehReactor reactor, VehPlan ai_plan, const char* name);
typedef int(__cdecl *Fact_airdrop)(int veh_id, int x, int y, int flags);
typedef int(__cdecl *Fact_destroy)(int veh_id, int flags, int x, int y);
typedef int(__cdecl *Fact_gate)(int veh_id, int base_id);
typedef int(__cdecl *Fhas_abil)(int unit_id, int ability_flag);
typedef int(__cdecl *Fhex_cost)(int unit_id, int faction_id, int x1, int y1, int x2, int y2, int a7);
typedef void(__cdecl *Fname_base)(int faction_id, char* name, bool save_offset, bool sea_base);
typedef int(__cdecl *Fveh_cost)(int item_id, int base_id, int* ptr);
typedef int(__cdecl *Fbase_at)(int x, int y);
typedef int(__cdecl *FPOP2)(const char* label, const char* pcx_filename, int a3);
typedef int(__cdecl *FPOP3)(const char* label, int a2, int a3, int a4, int a5);
typedef int(__cdecl *Fpopp)(
    const char* filename, const char* label, int a3, const char* pcx_filename, int a5);
typedef int(__cdecl *Fpopb)(
    const char* label, int flags, int sound_id, const char* pcx_filename, int a5);
typedef int (__cdecl *FX_pop)(const char* filename, const char* label, int a3, int a4, int a5, int a6);
typedef int (__cdecl *FX_pops)(
    const char* filename, const char* label, int a3, int a4, int a5, int a6, int a7, int a8, int a9);
typedef int(__cdecl *Fpop_ask_number)(const char *filename, const char* label, int value, int a4);
typedef int(__cdecl *Fname_proto)(char* name, int unit_id, int faction_id,
VehChassis chassis, VehWeapon weapon, VehArmor armor, VehAblFlag abls, VehReactor reactor);
typedef void(__cdecl *Fbattle_compute)(
    int veh_id_atk, int veh_id_def, int* offense_out, int* defense_out, int combat_type);
typedef void(__cdecl *Fbattle_kill)(
    int veh_id_def, int* a2, int* a3, int* credits_income, int veh_id_atk, int faction_id_atk);

typedef int(__cdecl *Fbase_draw)(Buffer* buffer, int base_id, int x, int y, int zoom, int opts);
typedef int(__cdecl *Fnet_energy)(int faction_id1, int faction_sum1, int faction_id2, int faction_sum2, int await_diplo);
typedef int(__cdecl *Fnet_tech)(int faction_id1, int tech_id, int faction_id2, int await_diplo);
typedef int(__cdecl *Fnet_loan)(int faction_id1, int faction_id2, int balance, int payment);
typedef int(__cdecl *Fsay_stats2)(char* dst, int unit_id);

typedef int(__cdecl *FGenString)(const char* name);
typedef int(__thiscall *FGenVoid)(void* This);
typedef int(__thiscall *FGenWin)(Win* This);
typedef int(__thiscall *FMapWin)(Console* This);
typedef int(__thiscall *FWin_is_visible)(Win* This);
typedef int(__thiscall *FTutWin_draw_arrow)(Win* This);
typedef int(__thiscall *FPlanWin_blink)(Win* This);
typedef int(__thiscall *FStringBox_clip_ids)(Win* This, int len);
typedef int(__stdcall *FWinProc)(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
typedef int(__cdecl *FWin_update_screen)(RECT* rc, int v1);
typedef int(__cdecl *FWin_flip)(RECT* rc);
typedef int(__thiscall *FBaseWin_zoom)(Win* This, int a2, int a3);
typedef int(__thiscall *FDesignWin_exec)(Win* This, int faction_id, int unit_id);
typedef int(__thiscall *FPopup_start)(
    Win* This, const char* filename, const char* label, int a4, int a5, int a6, int a7);
typedef int(__thiscall *FBasePop_start)(
    void* This, const char* filename, const char* label, int a4, int a5, int a6, int a7);
typedef int(__thiscall *FNetMsg)(void* This);
typedef int(__thiscall *FNetMsg_pop)(
    void* This, const char* label, int delay, int a4, const char* filename);
typedef int(__cdecl *FNetMsg_pop2)(const char* label, const char* filename);
typedef int(__thiscall *FBaseButton_text)(BaseButton* This, char* text);
typedef int(__cdecl *Fload_daemon)(const char* name, int flag);
typedef int(__cdecl *Fheader_check)(char* buf, FILE* file);
typedef int(__cdecl *Fheader_write)(const char* buf, FILE* file);

extern FGenString amovie_project;
extern FPOP2 POP2;
extern FPOP3 POP3;
extern FPopup_start Popup_start;
extern FGenWin BaseWin_focus;
extern FBaseWin_zoom BaseWin_zoom;
extern FGenWin BaseWin_nerve_staple;
extern FGenWin BaseWin_on_redraw;
extern FDesignWin_exec DesignWin_exec;
extern FGenVoid SubInterface_delete_iface_mode;
extern FGenVoid SubInterface_set_iface_mode;
extern FGenVoid SubInterface_release_iface_mode;
extern fp_none draw_cursor;
extern fp_4int draw_radius;
extern fp_3int draw_tile;
extern fp_4int draw_tile_fixup;
extern fp_6int draw_tile_fixup2;
extern fp_3int draw_tiles;
extern fp_1int draw_map;
extern FNetMsg NetMsg_close;
extern FNetMsg_pop NetMsg_pop;
extern FPlanWin_blink PlanWin_blink;
extern Fpopp popp;
extern Fpopb popb;
extern fp_none turn_timer;
//extern Fhas_abil has_abil;
extern FX_pop X_pop;
extern FX_pops X_pops;
extern FWin_flip Win_flip;
extern FWinProc WinProc;
extern fp_none Win_get_key_window;
extern FWin_update_screen Win_update_screen;
//extern FWin_is_visible Win_is_visible;
extern FBasePop_start BasePop_start;
extern FBaseButton_text BaseButton_set_bubble_text;
extern Fpop_ask_number pop_ask_number;
extern FStringBox_clip_ids StringBox_clip_ids;
extern fp_2int game_random; // renamed, seeded by game_reseed
extern fp_1int game_reseed; // renamed
extern fp_none game_rand;   // renamed, seeded by game_srand
extern fp_1int game_srand;  // renamed

typedef int(__thiscall *FConsole)(Console* This);
typedef int(__thiscall *FConsole_new_base)(Console* This, int a2);
typedef int(__thiscall *FConsole_skip)(Console* This, int a2);
typedef int(__thiscall *FConsole_wait)(Console* This, int a2);
typedef int(__thiscall *FConsole_unload)(Console* This, int a2);
typedef int(__thiscall *FConsole_upgrade)(Console* This, int a2);
typedef int(__thiscall *FConsole_sentry)(Console* This, int a2, int a3);
typedef int(__thiscall *FConsole_hold)(Console* This, int a2, int a3);
typedef int(__thiscall *FConsole_give_veh)(Console* This, int a2);
typedef int(__thiscall *FConsole_disband)(Console* This, int a2);
typedef int(__thiscall *FConsole_disband2)(Console* This, int a2, int a3);
typedef int(__thiscall *FConsole_activate)(Console* This, int a2, int a3, int a4);
typedef int(__thiscall *FConsole_terraform)(Console* This, int a2, int );
typedef int(__thiscall *FConsole_destroy)(Console* This, int a2);
typedef int(__thiscall *FConsole_oblit)(Console* This, int a2);
typedef int(__thiscall *FConsole_go_to)(Console* This, int a2, int a3);
typedef int(__thiscall *FConsole_road_to)(Console* This, int a2, int a3);
typedef int(__thiscall *FConsole_designate)(Console* This, int a2);
typedef int(__thiscall *FConsole_go_home)(Console* This, int a2);
typedef int(__thiscall *FConsole_set_patrol)(Console* This, int a2);
typedef int(__thiscall *FConsole_missile)(Console* This, int a2);
typedef int(__thiscall *FConsole_automate)(Console* This, int a2, int a3);
typedef int(__thiscall *FConsole_bomb_run)(Console* This, int a2, int a3, int a4);
typedef int(__thiscall *FConsole_set_road_to)(Console* This, int a2, int a3, int a4, int a5);
typedef int(__thiscall *FConsole_explore)(Console* This, int a2);
typedef int(__thiscall *FConsole_convoy)(Console* This, int a2);
typedef int(__thiscall *FConsole_arty)(Console* This, int a2);
typedef int(__thiscall *FConsole_group)(Console* This, int a2);
typedef int(__thiscall *FConsole_editor_who)(Console* This, int a2, int a3);
typedef int(__thiscall *FConsole_editor_edit_veh)(Console* This, int a2);
typedef int(__thiscall *FConsole_editor_delete_veh)(Console* This, int a2);
typedef int(__thiscall *FConsole_editor_paints)(Console* This, int a2);
typedef int(__thiscall *FConsole_editor_landmark)(Console* This, int a2);
typedef int(__thiscall *FConsole_Console)(Console* This, int a2);
typedef int(__thiscall *FConsole_cursor_on)(Console* This, int a2, int a3);
typedef int(__thiscall *FConsole_focus)(Console* This, int a2, int a3, int a4);
typedef int(__thiscall *FConsole_cursor_next)(Console* This, int a2, int a3);
typedef int(__thiscall *FConsole_ready_search)(Console* This, int a2);
typedef int(__thiscall *FConsole_set_view)(Console* This, int a2);
typedef int(__thiscall *FConsole_set_move)(Console* This, int a2);
typedef int(__thiscall *FConsole_set_cursor)(Console* This, int a2, int a3);
typedef int(__thiscall *FConsole_update_data)(Console* This, int a2);
typedef int(__thiscall *FConsole_set_ai)(Console* This, int a2);
typedef int(__thiscall *FConsole_set_research)(Console* This, int a2);
typedef int(__thiscall *FConsole_zoom)(Console* This, int zoom_type, int a3);
typedef int(__thiscall *FConsole_chat)(Console* This, int a2);
typedef int(__thiscall *FConsole_name_landmark)(Console* This, int a2, int a3);
typedef int(__thiscall *FConsole_erase_landmark)(Console* This, int a2, int a3);
typedef int(__thiscall *FConsole_cursor_key)(Console* This, int a2, int a3, int a4);
typedef int(__thiscall *FConsole_veh_key)(Console* This, int a2, int a3, int a4);
typedef int(__thiscall *FConsole_on_key_click)(Console* This, int a2, int a3);
typedef int(__thiscall *FConsole_load_proc)(Console* This, int a2, int a3);
typedef int(__thiscall *FConsole_iface_click)(Console* This, int a2);
typedef int(__thiscall *FConsole_init)(Console* This, int a2);

extern FConsole_new_base Console_new_base;
extern FConsole_skip Console_skip;
extern FConsole_wait Console_wait;
extern FConsole_unload Console_unload;
extern FConsole_upgrade Console_upgrade;
extern FConsole_sentry Console_sentry;
extern FConsole_hold Console_hold;
extern FConsole_give_veh Console_give_veh;
extern FConsole_disband Console_disband;
extern FConsole_disband2 Console_disband2;
extern FConsole_activate Console_activate;
extern FConsole_terraform Console_terraform;
extern FConsole_destroy Console_destroy;
extern FConsole_oblit Console_oblit;
extern FConsole_go_to Console_go_to;
extern FConsole_road_to Console_road_to;
extern FConsole_designate Console_designate;
extern FConsole_go_home Console_go_home;
extern FConsole_set_patrol Console_set_patrol;
extern FConsole_missile Console_missile;
extern FConsole_automate Console_automate;
extern FConsole_bomb_run Console_bomb_run;
extern FConsole_set_road_to Console_set_road_to;
extern FConsole_explore Console_explore;
extern FConsole_convoy Console_convoy;
extern FConsole_arty Console_arty;
extern FConsole_group Console_group;
extern FConsole Console_assemble;
extern FConsole Console_editor_on;
extern FConsole_editor_who Console_editor_who;
extern FConsole Console_editor_diplomacy;
extern FConsole Console_editor_reset_faction;
extern FConsole Console_editor_reset_tech;
extern FConsole Console_editor_personality;
extern FConsole Console_editor_strategy;
extern FConsole Console_editor_rules;
extern FConsole Console_editor_scen_rules;
extern FConsole Console_editor_scen_victory;
extern FConsole Console_editor_scen_param;
extern FConsole Console_custom_my_faction;
extern FConsole Console_editor_diff;
extern FConsole_editor_edit_veh Console_editor_edit_veh;
extern FConsole_editor_delete_veh Console_editor_delete_veh;
extern FConsole Console_editor_veh;
extern FConsole Console_editor_view;
extern FConsole Console_editor_tech;
extern FConsole Console_editor_energy;
extern FConsole Console_editor_date;
extern FConsole Console_editor_reload;
extern FConsole Console_editor_eliminate;
extern FConsole Console_editor_kill_vehicles;
extern FConsole Console_editor_save;
extern FConsole Console_editor_load;
extern FConsole_editor_paints Console_editor_paints;
extern FConsole Console_editor_minor_landmark;
extern FConsole Console_editor_terrain;
extern FConsole Console_editor_set_brush;
extern FConsole Console_editor_map_type;
extern FConsole Console_editor_polar;
extern FConsole Console_editor_climate;
extern FConsole Console_editor_generate;
extern FConsole Console_editor_fast;
extern FConsole Console_editor_resource_beacon;
extern FConsole Console_editor_clear_random;
extern FConsole Console_editor_clear;
extern FConsole Console_editor_clear_vehicles;
extern FConsole Console_editor_clear_terrain;
extern FConsole Console_editor_rockiness;
extern FConsole_editor_landmark Console_editor_landmark;
extern FConsole Console_editor_undo;
extern FConsole Console_editor_undo2;
extern FConsole Console_edit_lock;
extern FConsole Console_editor_lock2;
extern FConsole Console_corner_the_market;
extern FConsole_Console Console_Console;
extern FConsole_cursor_on Console_cursor_on;
extern FConsole Console_cursor_off;
extern FConsole Console_selected;
extern FConsole_focus Console_focus;
extern FConsole_cursor_next Console_cursor_next;
extern FConsole_ready_search Console_ready_search;
extern FConsole Console_ready;
extern FConsole_set_view Console_set_view;
extern FConsole_set_move Console_set_move;
extern FConsole Console_turn_hints;
extern FConsole Console_give_hints;
extern FConsole Console_veh_turn;
extern FConsole Console_human_turn;
extern FConsole_set_cursor Console_set_cursor;
extern FConsole_update_data Console_update_data;
extern FConsole Console_retire_game;
extern FConsole Console_set_preferences;
extern FConsole Console_set_adv_preferences;
extern FConsole Console_set_auto_preferences;
extern FConsole Console_set_base_preferences;
extern FConsole Console_set_audiovisual;
extern FConsole Console_set_map_display;
extern FConsole_set_ai Console_set_ai;
extern FConsole_set_research Console_set_research;
extern FConsole_zoom Console_zoom;
extern FConsole Console_center;
extern FConsole Console_survey;
extern FConsole_chat Console_chat;
extern FConsole Console_time_controls;
extern FConsole Console_show_movies;
extern FConsole_name_landmark Console_name_landmark;
extern FConsole_erase_landmark Console_erase_landmark;
extern FConsole Console_zoom_to_upkeep_base;
extern FConsole_cursor_key Console_cursor_key;
extern FConsole Console_end_my_turn;
extern FConsole Console_use_time_bonus;
extern FConsole_veh_key Console_veh_key;
extern FConsole_on_key_click Console_on_key_click;
extern FConsole_load_proc Console_load_proc;
extern FConsole_iface_click Console_iface_click;
extern fp_1int Console_iface_click2;
extern FConsole Console_close;
extern FConsole_init Console_init;

typedef int(__thiscall *FMapWin_MapWin)(Console* This, int a2);
typedef int(__thiscall *FMapWin_tile_to_pixel)(Console* This, int x, int y, long* px, long* py);
typedef int(__thiscall *FMapWin_pixel_to_tile)(Console* This, int x, int y, long* px, long* py);
typedef int(__thiscall *FMapWin_gen_terrain_poly)(
    Console* This, int a2, int zoom, int faction, int a5, int a6, int x, int y, int px, int py);
typedef int(__thiscall *FMapWin_compute_clip)(Console* This, int a2, int a3, int a4, LPRECT lprcDst);
typedef int(__thiscall *FMapWin_gen_radius)(Console* This, int x, int y, int a4, int faction, int a);
typedef int(__thiscall *FMapWin_gen_map)(Console* This, int faction, int units_only);
typedef int(__thiscall *FMapWin_draw_radius)(Console* This, int x, int y, int flag, int v1);
typedef int(__thiscall *FMapWin_draw_tile)(Console* This, int a2, int a3, int a4);
typedef int(__thiscall *FMapWin_draw_map)(Console* This, int a2);
typedef int(__thiscall *FMapWin_draw_cursor)(Console* This);
typedef int(__thiscall *FMapWin_set_center)(Console* This, int x, int y, int flag);
typedef int(__thiscall *FMapWin_focus)(Console* This, int x, int y);
typedef int(__thiscall *FMapWin_clear_alt)(Console* This, int a2, int a3, int a4);
typedef int(__thiscall *FMapWin_clear_terrain)(Console* This);
typedef int(__thiscall *FMapWin_get_relative_alt)(Console* This, int a2, int a3, int a4);
typedef int(__thiscall *FMapWin_get_alt)(Console* This, int a2, int a3, int a4);
typedef int(__thiscall *FMapWin_get_brighting)(Console* This, int a2, int a3, int a4);
typedef int(__thiscall *FMapWin_get_point_light)(Console* This, int a2, int a3, int a4);
typedef int(__thiscall *FMapWin_init2)(Console* This, int a2, int a3, int a4);
typedef int(__thiscall *FMapWin_init)(Console* This, int a2, int a3);

extern FMapWin_MapWin MapWin_MapWin;
extern FMapWin_MapWin MapWin_clear;
extern FMapWin MapWin_calculate_dimensions;
extern FMapWin_pixel_to_tile MapWin_pixel_to_tile;
extern FMapWin_tile_to_pixel MapWin_tile_to_pixel;
extern FMapWin_gen_terrain_poly MapWin_gen_terrain_poly;
extern FMapWin_compute_clip MapWin_compute_clip;
extern FMapWin_gen_radius MapWin_gen_radius;
extern FMapWin_gen_map MapWin_gen_map;
extern FMapWin_draw_radius MapWin_draw_radius;
extern FMapWin_draw_tile MapWin_draw_tile;
extern FMapWin_draw_map MapWin_draw_map;
extern FMapWin_draw_cursor MapWin_draw_cursor;
extern FMapWin_set_center MapWin_set_center;
extern FMapWin_focus MapWin_focus;
extern fp_none MapWin_main_caption;
extern FMapWin_clear_alt MapWin_clear_alt;
extern FMapWin_clear_terrain MapWin_clear_terrain;
extern FMapWin_get_relative_alt MapWin_get_relative_alt;
extern FMapWin_get_alt MapWin_get_alt;
extern fp_none MapWin_compute_lighting_table;
extern FMapWin_get_brighting MapWin_get_brighting;
extern FMapWin_get_point_light MapWin_get_point_light;
extern FMapWin_init2 MapWin_init2;
extern FMapWin_init MapWin_init;
extern FMapWin MapWin_init_dummy;
extern FMapWin MapWin_close;

typedef int(__thiscall *FGraphicWin_GraphicWin)(Win* This);
typedef int(__thiscall *FGraphicWin_dtor)(Win* This);
typedef int(__thiscall *FGraphicWin_close)(Win* This);
typedef int(__thiscall *FGraphicWin_init)(
    Win* This, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10);
typedef int(__thiscall *FGraphicWin_init2)(Win* This, int* a2, char* a3, int a4, int a5, int a6, int a7);
typedef int(__thiscall *FGraphicWin_fill)(Win* This, int a2);
typedef int(__thiscall *FGraphicWin_fill2)(Win* This, RECT* rc, int a3);
typedef int(__thiscall *FGraphicWin_fill3)(Win* This, int x, int y, int a4, int a5, int a6);
typedef int(__thiscall *FGraphicWin_load_pcx)(Win* This, char* a1, int a2, int a3, int a4, int a5);
typedef int(__thiscall *FGraphicWin_resize)(Win* This, int a2, int a3, int a4);
typedef int(__thiscall *FGraphicWin_update3)(Win* This, int a2, int a3, int a4, int a5, int a6);
typedef int(__thiscall *FGraphicWin_update2)(Win* This, RECT* rc, int a3);
typedef int(__thiscall *FGraphicWin_update)(Win* This, int a2);
typedef int(__thiscall *FGraphicWin_soft_update3)(Win* This, LONG a2, LONG a3, int a4, int a5);
typedef int(__thiscall *FGraphicWin_soft_update2)(Win* This);
typedef int(__thiscall *FGraphicWin_soft_update)(Win* This, RECT* rc);
typedef int(__thiscall *FGraphicWin_redraw)(Win* This);
typedef int(__thiscall *FGraphicWin_delete)(Win* This, int a2);

extern FGraphicWin_GraphicWin GraphicWin_GraphicWin;
extern FGraphicWin_dtor GraphicWin_dtor;
extern FGraphicWin_close GraphicWin_close;
extern FGraphicWin_init GraphicWin_init;
extern FGraphicWin_init2 GraphicWin_init2;
extern FGraphicWin_fill GraphicWin_fill;
extern FGraphicWin_fill2 GraphicWin_fill2;
extern FGraphicWin_fill3 GraphicWin_fill3;
extern FGraphicWin_load_pcx GraphicWin_load_pcx;
extern FGraphicWin_resize GraphicWin_resize;
extern FGraphicWin_update3 GraphicWin_update3;
extern FGraphicWin_update2 GraphicWin_update2;
extern FGraphicWin_update GraphicWin_update;
extern FGraphicWin_soft_update3 GraphicWin_soft_update3;
extern FGraphicWin_soft_update2 GraphicWin_soft_update2;
extern FGraphicWin_soft_update GraphicWin_soft_update;
extern FGraphicWin_redraw GraphicWin_redraw;
extern FGraphicWin_delete GraphicWin_delete;

typedef int(__thiscall *FBattleWin_battle_report)(Win* This, int a2, int a3, int a4, int a5, int a6);

extern FGenWin BattleWin_init;
extern FGenWin BattleWin_pulse_timer;
extern FGenWin BattleWin_stop_timer;
extern FBattleWin_battle_report BattleWin_battle_report;
extern FGenWin BattleWin_clear;
extern FGenWin BattleWin_BattleWin;

typedef int(__thiscall *FStatusWin_set_title)(Win* This, int a2);
typedef int(__thiscall *FStatusWin_draw_active)(Win* This, int a2, int a3, int a4);
typedef int(__thiscall *FStatusWin_draw_status)(Win* This, int a2, int a3, int a4, int a5, int a6);
typedef int(__thiscall *FStatusWin_draw)(Win* This, int a2, int a3, int a4, int a5, int a6);
typedef int(__thiscall *FStatusWin_on_left_double_click)(Win* This, int a2, int a3);
typedef int(__thiscall *FStatusWin_on_left_click)(Win* This, int a2, int a3);
typedef int(__thiscall *FStatusWin_on_right_click)(Win* This, int a2, int a3, int a4);
typedef int(__thiscall *FStatusWin_set_loc)(Win* This, int a2, int a3);

extern FStatusWin_set_title StatusWin_set_title;
extern FStatusWin_draw_active StatusWin_draw_active;
extern FGenWin StatusWin_reset_active;
extern FStatusWin_draw_status StatusWin_draw_status;
extern FStatusWin_draw StatusWin_draw;
extern FGenWin StatusWin_on_redraw;
extern FGenWin StatusWin_reset;
extern FStatusWin_on_left_double_click StatusWin_on_left_double_click;
extern FGenWin StatusWin_arrow_left;
extern FGenWin StatusWin_arrow_right;
extern FStatusWin_on_left_click StatusWin_on_left_click;
extern FStatusWin_on_right_click StatusWin_on_right_click;
extern FGenWin StatusWin_redraw;
extern FStatusWin_set_loc StatusWin_set_loc;
extern FGenWin StatusWin_init;

typedef int(__thiscall *FTutWin_do_base)(Win* This, int a2, int a3);
typedef int(__thiscall *FTutWin_iface_rect)(Win* This, int a2, int a3);
typedef int(__thiscall *FTutWin_base_rect)(Win* This, int a2, int a3);
typedef int(__thiscall *FTutWin_soc_rect)(Win* This, int a2, int a3);
typedef int(__thiscall *FTutWin_des_rect)(Win* This, int a2, int a3);
typedef int(__thiscall *FTutWin_tut_win)(Win* This, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9);
typedef int(__thiscall *FTutWin_tut_map)(Win* This, const char* label, int a3, int a4, int a5, int a6, int a7, int a8, int a9);
typedef int(__thiscall *FTutWin_delete)(Win* This, char a2);

extern fp_1int tut_check;
extern fp_1int tut_check2;
extern FGenWin TutWin_TutWin;
extern FGenWin TutWin_clear;
extern FTutWin_do_base TutWin_do_base;
extern FTutWin_iface_rect TutWin_iface_rect;
extern FTutWin_base_rect TutWin_base_rect;
extern FTutWin_soc_rect TutWin_soc_rect;
extern FTutWin_des_rect TutWin_des_rect;
extern FGenWin TutWin_tour;
extern FGenWin TutWin_reset;
extern FGenWin TutWin_draw_arrow;
extern FTutWin_tut_win TutWin_tut_win;
extern FTutWin_tut_map TutWin_tut_map;
extern FTutWin_delete TutWin_delete;

typedef int(__thiscall *FBuffer_Buffer)(Buffer* This);
typedef int(__thiscall *FBuffer_resize)(Buffer* This, int a2, int a3);
typedef int(__thiscall *FBuffer_load_pcx)(Buffer* This, char* filename, int a3, int a4, int a5);
typedef int(__thiscall *FBuffer_set_clip)(Buffer* This, RECT* rc);
typedef int(__thiscall *FBuffer_set_clip_)(Buffer* This, int xLeft, int yTop, int a4, int a5);
typedef int(__thiscall *FBuffer_fill)(Buffer* This, int x, int y, int w, int h, int a6);
typedef int(__thiscall *FBuffer_draw2)(Buffer* src, Buffer* dst, RECT* rc, int xDst, int yDst);
typedef int(__thiscall *FBuffer_draw)(Buffer* src, Buffer* dst, int a3, int a4, int a5, int a6, int a7);
typedef int(__thiscall *FBuffer_draw_mono)(Buffer* This, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
typedef int(__thiscall *FBuffer_draw_0)(Buffer* This, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
typedef int(__thiscall *FBuffer_draw_multi_table_dest)(
    Buffer* This, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
typedef int(__thiscall *FBuffer_copy4)(Buffer* This, int a1, int a2, int a3, int a4, int a5);
typedef int(__thiscall *FBuffer_copy3)(Buffer* This, int a1, DWORD* a2);
typedef int(__thiscall *FBuffer_copy2)(
    Buffer* src, Buffer* dst, int xSrc, int ySrc, int wSrc, int hSrc, int xDst, int yDst, int wDst, int hDst);
typedef int(__thiscall *FBuffer_set_font)(Buffer* This, Font* font, int a3, int a4, int a5);
typedef int(__thiscall *FBuffer_set_text_color)(Buffer* This, int color, int a3, int a4, int a5);
typedef int(__thiscall *FBuffer_set_text_color2)(Buffer* This, int a2, int a3, int a4, int a5);
typedef int(__thiscall *FBuffer_set_text_color3)(Buffer* This, int a2, int a3, int a4, int a5);
typedef int(__thiscall *FBuffer_set_text_color_hyper)(Buffer* This, int a2, int a3, int a4, int a5);
typedef int(__thiscall *FBuffer_write_strings_height)(Buffer* This, DWORD* a2, int a3, int a4);
typedef int(__thiscall *FBuffer_write_strings)(Buffer* This, int a2, int a3, int y, int a5, char a6);
typedef int(__thiscall *FBuffer_write_l)(Buffer* This, LPCSTR lpString, int x, int y, int max_len);
typedef int(__thiscall *FBuffer_write_l2)(Buffer* This, LPCSTR lpString, RECT* rc, int max_len);
typedef int(__thiscall *FBuffer_write_cent_l)(Buffer* This, LPCSTR lpString, int x, int y, int w, int max_len);
typedef int(__thiscall *FBuffer_write_cent_l2)(Buffer* This, LPCSTR lpString, int a3, int a4, int a5, int a6, int max_len);
typedef int(__thiscall *FBuffer_write_cent_l3)(Buffer* This, LPCSTR lpString, RECT* rc, int max_len);
typedef int(__thiscall *FBuffer_write_cent_l4)(Buffer* This, LPCSTR lpString, int x, int y, int max_len);
typedef int(__thiscall *FBuffer_write_right_l)(Buffer* This, LPCSTR lpString, int x, int y, int a5, int a6);
typedef int(__thiscall *FBuffer_write_right_l2)(Buffer* This, LPCSTR lpString, int x, int y, int max_len);
typedef int(__thiscall *FBuffer_write_right_l3)(Buffer* This, LPCSTR lpString, int a3, int a4);
typedef int(__thiscall *FBuffer_wrap)(Buffer* This, LPCSTR lpString, int a3);
typedef int(__thiscall *FBuffer_wrap2)(Buffer* This, LPCSTR lpString, int x, int y, int a5);
typedef int(__thiscall *FBuffer_wrap_cent)(Buffer* This, LPCSTR lpString, int a3, int y, int a5);
typedef int(__thiscall *FBuffer_wrap_cent3)(Buffer* This, LPCSTR lpString, int a3);
typedef int(__thiscall *FBuffer_change_color)(Buffer* This, char a2, char a3);
typedef int(__thiscall *FBuffer_sync_to_palette)(Buffer* This, Palette* a2);
typedef int(__thiscall *FBuffer_write_pcx)(Buffer* This, char* filename);
typedef int(__thiscall *FBuffer_fill2)(Buffer* This, int a2);
typedef int(__thiscall *FBuffer_fill3)(Buffer* This, RECT* rc, int a3);
typedef int(__thiscall *FBuffer_copy)(
    Buffer* src, Buffer* dst, int xSrc, int ySrc, int xDst, int yDst, int wSrc, int hSrc);
typedef int(__thiscall *FBuffer_line)(
    Buffer* This, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10);
typedef int(__thiscall *FBuffer_line_0)(Buffer* This, int x1, int y1, int x2, int y2, int color);
typedef int(__thiscall *FBuffer_hline)(Buffer* This, int x1, int x2, int y1, int color);
typedef int(__thiscall *FBuffer_vline)(Buffer* This, int a2, int a3, int a4, char color);
typedef int(__thiscall *FBuffer_dotted_vline)(Buffer* This, int a2, int a3, int a4, char a5);
typedef int(__thiscall *FBuffer_get_pixel)(Buffer* This, int a2, int a3);
typedef int(__cdecl *FBuffer_get_pcx_dimensions)(char* filename, int a2, int a3);
typedef int(__thiscall *FBuffer_load_pcx2)(Buffer* This, int a2, int a3, int a4, int a5, int a6);
typedef int(__thiscall *FBuffer_copy_mask)(
    Buffer* This, const RECT* rc, int a3, int a4, LONG a5, LONG a6, int a7, int a8, char a9);
typedef int(__thiscall *FBuffer_box_sprite)(Buffer* This, int* a2, DWORD* a3);
typedef int(__thiscall *FBuffer_box)(Buffer* This, RECT* rc, int color_h, int color_v);

extern FBuffer_Buffer Buffer_Buffer;
extern FBuffer_Buffer Buffer_dtor;
extern FBuffer_Buffer Buffer_close;
extern FBuffer_resize Buffer_resize;
extern FBuffer_load_pcx Buffer_load_pcx;
extern FBuffer_set_clip Buffer_set_clip;
extern FBuffer_set_clip_ Buffer_set_clip_;
extern FBuffer_fill Buffer_fill;
extern FBuffer_draw2 Buffer_draw2;
extern FBuffer_draw Buffer_draw;
extern FBuffer_draw_mono Buffer_draw_mono;
extern FBuffer_draw_0 Buffer_draw_0;
extern FBuffer_draw_multi_table_dest Buffer_draw_multi_table_dest;
extern FBuffer_copy4 Buffer_copy4;
extern FBuffer_copy3 Buffer_copy3;
extern FBuffer_copy2 Buffer_copy2;
extern FBuffer_set_font Buffer_set_font;
extern FBuffer_set_text_color Buffer_set_text_color;
extern FBuffer_set_text_color2 Buffer_set_text_color2;
extern FBuffer_set_text_color3 Buffer_set_text_color3;
extern FBuffer_set_text_color_hyper Buffer_set_text_color_hyper;
extern FBuffer_write_strings_height Buffer_write_strings_height;
extern FBuffer_write_strings Buffer_write_strings;
extern FBuffer_write_l Buffer_write_l;
extern FBuffer_write_l2 Buffer_write_l2;
extern FBuffer_write_cent_l Buffer_write_cent_l;
extern FBuffer_write_cent_l2 Buffer_write_cent_l2;
extern FBuffer_write_cent_l3 Buffer_write_cent_l3;
extern FBuffer_write_cent_l4 Buffer_write_cent_l4;
extern FBuffer_write_right_l Buffer_write_right_l;
extern FBuffer_write_right_l2 Buffer_write_right_l2;
extern FBuffer_write_right_l3 Buffer_write_right_l3;
extern FBuffer_wrap Buffer_wrap;
extern FBuffer_wrap2 Buffer_wrap2;
extern FBuffer_wrap_cent Buffer_wrap_cent;
extern FBuffer_wrap_cent3 Buffer_wrap_cent3;
extern FBuffer_change_color Buffer_change_color;
extern FBuffer_sync_to_palette Buffer_sync_to_palette;
extern FBuffer_Buffer Buffer_clear_links;
extern FBuffer_write_pcx Buffer_write_pcx;
extern FBuffer_fill2 Buffer_fill2;
extern FBuffer_fill3 Buffer_fill3;
extern FBuffer_copy Buffer_copy;
extern FBuffer_line Buffer_line;
extern FBuffer_line_0 Buffer_line_0;
extern FBuffer_hline Buffer_hline;
extern FBuffer_vline Buffer_vline;
extern FBuffer_dotted_vline Buffer_dotted_vline;
extern FBuffer_get_pixel Buffer_get_pixel;
extern FBuffer_get_pcx_dimensions Buffer_get_pcx_dimensions;
extern FBuffer_load_pcx2 Buffer_load_pcx2;
extern FBuffer_copy_mask Buffer_copy_mask;
extern FBuffer_box_sprite Buffer_box_sprite;
extern FBuffer_box Buffer_box;

typedef int(__thiscall *FFX_init)(void* This);
typedef int(__thiscall *FFX_play2)(void* This, int a2, int a3, int a4);
typedef int(__thiscall *FFX_play)(void* This, int a2);

extern FFX_init FX_init;
extern FFX_play2 FX_play2;
extern FFX_play FX_play;
extern FFX_play FX_stop;
extern FFX_play FX_fade;
extern FFX_play FX_engine_pitch;

typedef int(__thiscall *FLock)(void* This);
typedef int(__thiscall *FLock_unlock)(void* This, int a2);
typedef int(__thiscall *FLock_check_global_2)(void* This, int a2);
typedef int(__thiscall *FLock_global_lock)(void* This, int a2);
typedef int(__thiscall *FLock_lock)(void* This, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
typedef int(__thiscall *FLock_add_lock)(void* This, int a2, int a3, int a4, int a5);

extern FLock Lock_clear;
extern FLock_unlock Lock_unlock;
extern FLock Lock_check_global;
extern FLock_check_global_2 Lock_check_global_2;
extern FLock_global_lock Lock_global_lock;
extern FLock_lock Lock_lock;
extern FLock_add_lock Lock_add_lock;
extern FLock Lock_any_locks;

typedef int(__thiscall *FTime)(Time* This);
typedef int(__thiscall *FTime_init)(Time* This, int a2, int a3, int a4, int a5);
typedef int(__thiscall *FTime_init2)(Time* This, int a2, int a3, int a4, int a5, int a6);
typedef int(__thiscall *FTime_start)(Time* This, int a2, int a3, size_t uDelay, size_t uResolution);
typedef int(__thiscall *FTime_start2)(Time* This, int a2, int a3, int a4, size_t uDelay, size_t uResolution);
typedef int(__thiscall *FTime_pulse)(Time* This, int a2, int a3, size_t uDelay, size_t uResolution);
typedef int(__thiscall *FTime_pulse2)(Time* This, int a2, int a3, int a4, size_t uDelay, size_t uResolution);

extern FTime Time_Time;
extern FTime Time_dtor;
extern FTime_init Time_init;
extern FTime_init2 Time_init2;
extern FTime_start Time_start;
extern FTime_start2 Time_start2;
extern FTime_pulse Time_pulse;
extern FTime_pulse2 Time_pulse2;
extern FTime Time_start3;
extern FTime Time_pulse3;
extern FTime Time_stop;
extern FTime Time_close;
extern fp_4int Time_TimerFunc1;
extern fp_5int Time_TimerFunc2;
extern FTime Time_set_modal;
extern FTime Time_release_modal;
extern fp_none Time_init_class;
extern fp_none Time_close_class;

typedef int(__thiscall *FFontQueue_get_zoom)(Font* This, int a2, int a3, int a4, int a5);
typedef int(__thiscall *FFont_Font)(Font* This);
typedef int(__thiscall *FFont_init2)(Font* This, char* a2, int a3, int a4);
typedef int(__thiscall *FFont_init)(Font* This, const char* lpszFile, char* a3, int a4, int a5);
typedef int(__thiscall *FFont_close)(Font* This);
typedef int(__thiscall *FFont_width)(Font* This, const char* lpString);
typedef int(__thiscall *FFont_width2)(Font* This, const char* lpString, int a3);
typedef int(__thiscall *FFont_find_line_break_l)(Font* This, const char* lpString, int a3, int a4);
typedef int(__cdecl *FFont_init_font_class)(Font* a1);
typedef int(__cdecl *FFont_close_font_class)();

extern FFontQueue_get_zoom FontQueue_get_zoom;
extern FFont_Font Font_Font;
extern FFont_Font Font_dtor;
extern FFont_init2 Font_init2;
extern FFont_init Font_init;
extern FFont_Font Font_close;
extern FFont_width Font_width;
extern FFont_width2 Font_width2;
extern FFont_find_line_break_l Font_find_line_break_l;
extern FFont_init_font_class Font_init_font_class;
extern FFont_close_font_class Font_close_font_class;

typedef int(__thiscall *FPath_init)(Path* This);
typedef int(__thiscall *FPath_shutdown)(Path* This);
typedef int(__thiscall *FPath_zoc_path)(Path* This, int a1, int a2, int a3);
typedef int(__thiscall *FPath_find)(
    Path* This, int x1, int y1, int x2, int y2, int unit_id, int faction_id, int a8, int a9);
typedef int(__thiscall *FPath_move)(Path* This, int veh_id, int faction_id);
typedef int(__thiscall *FPath_territory)(Path* This, int a2, int a3, int a4, int a5);
typedef int(__thiscall *FPath_continent)(Path* This, int a2, int a3, int a4);
typedef int(__thiscall *FPath_continents)(Path* This);
typedef int(__thiscall *FPath_sensors)(Path* This, int a2, int* a3, int* a4);

extern FPath_init Path_init;
extern FPath_shutdown Path_shutdown;
extern FPath_zoc_path Path_zoc_path;
extern FPath_find Path_find;
extern FPath_move Path_move;
extern fp_none Path_make_abstract;
extern FPath_territory Path_territory;
extern FPath_continent Path_continent;
extern FPath_continents Path_continents;
extern FPath_sensors Path_sensors;

typedef int(__thiscall *FAlphaNet)(AlphaNet* This);
typedef int(__thiscall *FAlphaNet_pid_2_idx)(AlphaNet* This, int a2);
typedef int(__thiscall *FAlphaNet_pid_2_who)(AlphaNet* This, int a2);
typedef int(__thiscall *FAlphaNet_who_2_pid)(AlphaNet* This, int a2);
typedef int(__thiscall *FAlphaNet_who_2_idx)(AlphaNet* This, int a2);
typedef int(__thiscall *FAlphaNet_pick_service)(AlphaNet* This, int a2);
typedef int(__thiscall *FAlphaNet_setup)(AlphaNet* This, int a2);
typedef int(__thiscall *FAlphaNet_do_join_dialog_and_connect)(AlphaNet* This, int a2, int a3);
typedef int(__thiscall *FAlphaNet_do_create_dialog_and_connect)(AlphaNet* This, int a2, int a3, int a4);

extern FAlphaNet AlphaNet_AlphaNet;
extern FAlphaNet AlphaNet_close;
extern FAlphaNet_pid_2_idx AlphaNet_pid_2_idx;
extern FAlphaNet_pid_2_who AlphaNet_pid_2_who;
extern FAlphaNet_who_2_pid AlphaNet_who_2_pid;
extern FAlphaNet_who_2_idx AlphaNet_who_2_idx;
extern FAlphaNet_pick_service AlphaNet_pick_service;
extern fp_none AlphaNet_do_create;
extern FAlphaNet AlphaNet_do_join;
extern FAlphaNet_setup AlphaNet_setup;
extern FAlphaNet_do_join_dialog_and_connect AlphaNet_do_join_dialog_and_connect;
extern FAlphaNet_do_create_dialog_and_connect AlphaNet_do_create_dialog_and_connect;

typedef int(__thiscall *FNetDaemon)(AlphaNet* This);
typedef int(__thiscall *FNetDaemon_init)(AlphaNet* This, int a2);
typedef int(__thiscall *FNetDaemon_game_checksum)(AlphaNet* This, int a2);
typedef int(__thiscall *FNetDaemon_wait)(AlphaNet* This, int a2, void* a3, int a4, int a5);
typedef int(__thiscall *FNetDaemon_open_channel)(AlphaNet* This, int a2, int a3);
typedef int(__thiscall *FNetDaemon_lock)(AlphaNet* This, int a2, int a3, int a4, int a5, int a6, int a7);
typedef int(__thiscall *FNetDaemon_add_lock)(AlphaNet* This, int a2, int a3, int a4);
typedef int(__thiscall *FNetDaemon_lock_base)(AlphaNet* This, int a2, int a3, int a4, int a5);
typedef int(__thiscall *FNetDaemon_unlock_base)(AlphaNet* This, int a2);
typedef int(__thiscall *FNetDaemon_lock_veh)(AlphaNet* This, void* a2, int a3, int a4, int a5, int a6);
typedef int(__thiscall *FNetDaemon_automated_lock)(AlphaNet* This, void* a2, int a3);
typedef int(__thiscall *FNetDaemon_await_exec)(AlphaNet* This, int a2);
typedef int(__thiscall *FNetDaemon_await_diplo)(AlphaNet* This, int a2);
typedef int(__thiscall *FNetDaemon_maybe_lock)(AlphaNet* This, int a2, int a3, int a4, int a5, int a6, int a7);
typedef int(__thiscall *FNetDaemon_order_veh)(AlphaNet* This, int a2, int a3, int a4);
typedef int(__thiscall *FNetDaemon_veh_drop)(AlphaNet* This, int a2, int a3, int a4);
typedef int(__thiscall *FNetDaemon_action)(AlphaNet* This, int a2, int a3);
typedef int(__thiscall *FNetDaemon_send_message)(AlphaNet* This, void* a2, int a3, int a4);
typedef int(__thiscall *FNetDaemon_synch)(AlphaNet* This, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
typedef int(__thiscall *FNetDaemon_fixup_message)(AlphaNet* This, void* a2);
typedef int(__fastcall *FNetDaemon_process_message)(AlphaNet* This, int a2, int a3, int a4, int a5);

extern FNetDaemon NetDaemon_cleanup;
extern FNetDaemon_init NetDaemon_init;
extern FNetDaemon NetDaemon_hang_up;
extern FNetDaemon NetDaemon_send_game;
extern FNetDaemon NetDaemon_send_files;
extern FNetDaemon NetDaemon_send_rules;
extern FNetDaemon_game_checksum NetDaemon_game_checksum;
extern FNetDaemon NetDaemon_receive;
extern FNetDaemon NetDaemon_net_tasks;
extern FNetDaemon_wait NetDaemon_wait;
extern FNetDaemon_open_channel NetDaemon_open_channel;
extern FNetDaemon NetDaemon_close_channel;
extern FNetDaemon_lock NetDaemon_lock;
extern FNetDaemon_add_lock NetDaemon_add_lock;
extern FNetDaemon NetDaemon_add_global;
extern FNetDaemon NetDaemon_unlock;
extern FNetDaemon_lock_base NetDaemon_lock_base;
extern FNetDaemon_unlock_base NetDaemon_unlock_base;
extern FNetDaemon_lock_veh NetDaemon_lock_veh;
extern FNetDaemon NetDaemon_unlock_veh;
extern FNetDaemon_automated_lock NetDaemon_automated_lock;
extern FNetDaemon_await_exec NetDaemon_await_exec;
extern FNetDaemon NetDaemon_await_synch;
extern FNetDaemon_await_diplo NetDaemon_await_diplo;
extern FNetDaemon_maybe_lock NetDaemon_maybe_lock;
extern FNetDaemon_order_veh NetDaemon_order_veh;
extern FNetDaemon_veh_drop NetDaemon_veh_drop;
extern FNetDaemon_action NetDaemon_action;
extern FNetDaemon_send_message NetDaemon_send_message;
extern FNetDaemon_synch NetDaemon_synch;
extern FNetDaemon_fixup_message NetDaemon_fixup_message;
extern FNetDaemon_process_message NetDaemon_process_message;

typedef int(__thiscall *FNet)(AlphaNet* This);
typedef int(__thiscall *FNet_init)(AlphaNet* This, int net_vals, int net_flag, int net_ver);
typedef int(__thiscall *FNet_check_for_lobby)(AlphaNet* This, char* a2, int a3, int a4, int a5);
typedef int(__thiscall *FNet_start_voice)(AlphaNet* This, int a2);
typedef int(__thiscall *FNet_poll_services)(AlphaNet* This, int a2);
typedef int(__thiscall *FNet_join_service)(AlphaNet* This, int a2);
typedef int(__thiscall *FNet_join_session)(AlphaNet* This, int a2, int a3, int a4);
typedef int(__thiscall *FNet_send_group)(AlphaNet* This, NetFifo* a2, size_t a3, int a4, int a5);
typedef int(__thiscall *FNet_send_packet_type)(AlphaNet* This, NetFifo* a2, size_t a3, int a4, int a5, int a6);
typedef int(__thiscall *FNet_send)(AlphaNet* This, NetFifo* a2, int a3, int a4, int a5);
typedef int(__thiscall *FNet_get)(AlphaNet* This, int a2, int a3);
typedef int(__thiscall *FNet_get_player_name)(AlphaNet* This, int a2);
typedef int(__thiscall *FNet_drop_player)(AlphaNet* This, int a2, int a3);
typedef int(__thiscall *FNetFifo)(NetFifo* This);
typedef int(__thiscall *FNetFifo_add)(NetFifo* This, int a2, int a3, int a4, int a5, int a6);
typedef int(__thiscall *FNetFifo_get)(NetFifo* This, int a2, int a3, int a4, int a5);

extern FNet Net_Net;
extern FNet_init Net_init;
extern FNet_check_for_lobby Net_check_for_lobby;
extern FNet_start_voice Net_start_voice_1;
extern FNet_start_voice Net_start_voice_2;
extern FNet Net_stop_voice;
extern FNet Net_close;
extern FNet_poll_services Net_poll_services;
extern FNet_join_service Net_join_service;
extern FNet_join_session Net_join_session;
extern FNet_send_group Net_send_group;
extern FNet_send_packet_type Net_send_packet_type;
extern FNet_send Net_send;
extern FNet_get Net_get;
extern FNet_get_player_name Net_get_player_name;
extern FNet Net_process_voice;
extern FNet Net_enable_join;
extern FNet Net_check_polling;
extern FNet_drop_player Net_drop_player;
extern FNetFifo NetFifo_NetFifo;
extern FNetFifo NetFifo_dtor;
extern FNetFifo NetFifo_close;
extern FNetFifo_add NetFifo_add;
extern FNetFifo_get NetFifo_get;

extern fp_1int wave_it;
extern fp_none ok_callback;
extern fp_1int load_music;
extern fp_1int ambience;
extern fp_1int ambience_veh;
extern fp_1int hall_of_fame;
extern fp_2int tech_heck;
extern fp_4int help_tech_info;
extern fp_3int help_tech_info2;
extern fp_1int help_project;
extern fp_none help_any;
extern fp_2int help_topic;
extern fp_3int help_create_link;

extern fp_none load_voxels;
extern fp_none load_palette;
extern fp_none load_terrain;
extern fp_1int load_faction_art;
extern fp_none load_box_sprites;
extern fp_none load_flags;
extern fp_none load_vehicles;
extern fp_none load_icons;
extern fp_none load_misc;
extern fp_none load_cursors;
extern fp_none load_cycling;
extern fp_none load_interface;
extern fp_none load_deswin_sprites;
extern fp_none load_fixed_sprites;
extern fp_none load_sprites;

extern fp_1int monument;
extern fp_none clear_monument;
extern fp_2int mon_colony_founded;
extern fp_2int mon_tech_discovered;
extern fp_1int mon_secrets_of_tech;
extern fp_1int mon_prototype_built;
extern fp_2int mon_facility_built;
extern fp_2int mon_secret_project;
extern fp_2int mon_enemy_destroyed;
extern fp_2int mon_conquer_base;
extern fp_1int mon_naval_unit_built;
extern fp_1int mon_air_unit_built;
extern fp_1int mon_native_life_bred;
extern fp_1int mon_first_in_space;
extern fp_1int mon_built_preserve;
extern fp_2int mon_winning_unify;
extern fp_2int mon_winning_trans;
extern fp_2int mon_killed_faction;
extern fp_3int say_morale2;
extern fp_2int say_morale;
extern fp_2int say_orders;
extern fp_1int say_orders2;

extern fp_3int terraform_cost;
extern fp_2int action_build;
//extern fp_2int contribution;
extern fp_3int action_terraform;
extern fp_1int action_staple;
extern Fact_destroy action_destroy;
extern fp_1int action_go_to;
extern fp_1int action_road_to;
extern fp_2int action_home;
extern Fact_airdrop action_airdrop;
extern fp_3int action_arty;
extern fp_1int action_destruct;
extern fp_2int action_oblit;
extern fp_3int valid_patrol;
extern fp_3int action_patrol;
extern fp_5int shoot_it;
extern fp_3int action_tectonic;
extern fp_3int action_fungal;
extern fp_2int action_give;
extern Fact_gate action_gate;
extern fp_4int action_sat_attack;
extern fp_1int action;

//extern fp_1int set_base;
extern fp_2int say_base;
//extern Fbase_at base_at;
extern fp_2int base_find;
extern fp_3int base_find2;
extern fp_6int base_find3;
//extern fp_5int whose_territory;
extern fp_3int base_territory;
//extern fp_none best_specialist;
extern Fname_base name_base;
extern fp_1int base_mark;
extern fp_3int cost_factor;
extern fp_2int base_making;
extern fp_1int base_lose_minerals;
//extern fp_3int set_fac;
//extern fp_3int is_coast;
//extern fp_1int base_first;
extern fp_3int base_init;
extern fp_1int base_kill;
extern fp_2int base_change;
extern fp_2int base_reset;
extern fp_3int bases_reset;
//extern fp_3int morale_mod;
//extern fp_2int breed_mod;
//extern fp_2int worm_mod;
extern fp_none farm_compute;
extern fp_5int crop_yield;
extern fp_5int mine_yield;
extern fp_5int energy_yield;
//extern fp_5int resource_yield;
extern fp_none base_yield;
extern fp_none base_support;
extern fp_none base_nutrient;
extern fp_none base_minerals;
extern fp_1int black_market;
extern fp_3int psych_check;
extern fp_none base_psych;
extern fp_2int base_rank;
extern fp_none base_energy;
//extern fp_1int base_compute;
extern fp_1int base_connect;
extern fp_1int base_terraform;
extern fp_1int pop_goal;
extern fp_none base_growth;
extern fp_3int do_upgrade;
extern fp_3int upgrade_cost;
extern fp_4int upgrade_prototype;
extern fp_2int upgrade_prototypes;
extern fp_1int upgrade_any_prototypes;
extern fp_1int base_queue;
extern fp_none base_production;
extern fp_none base_hurry;
extern fp_none base_check_support;
extern fp_none base_energy_costs;
extern fp_none base_research;
extern fp_none drone_riot;
extern fp_none base_drones;
extern fp_none base_doctors;
//extern fp_2int fac_maint;
extern fp_none base_maint;
extern fp_none base_ecology;
extern fp_1int base_upkeep;
extern fp_1int make_base_unique;
//extern fp_2int x_dist;
//extern fp_2int has_project;
extern fp_6int base_claimed;
extern fp_4int base_build;

//extern fp_1int drop_range;
extern fp_1int planet_buster2;
extern fp_1int planet_buster;
extern fp_4int shoot;
extern fp_3int planet_busting;
extern fp_5int defense_value;
extern fp_2int morale_alien;
//extern fp_4int psi_factor;
extern fp_5int get_basic_offense;
extern fp_4int get_basic_defense;
extern Fbattle_compute battle_compute;
extern fp_3int best_defender;
extern fp_3int boom;
extern fp_none sub_505D40;
extern fp_none sub_505D60;
extern Fbattle_kill battle_kill;
extern Fbattle_kill battle_kill_stack;
//extern fp_1int promote;
extern fp_1int invasions;
extern fp_4int interceptor;
extern Fbattle_fight_1 battle_fight_1; // renamed
extern Fbattle_fight_2 battle_fight_2; // renamed
extern fp_1int say_num;
extern fp_4int POP3_;
extern fp_1int sub_50B8F0;
extern fp_1int sub_50B910;
//extern fp_1int parse_set;
extern fp_3int sub_50B970;
extern fp_1int sub_50B9A0;
extern fp_2int sub_50B9C0;
extern FNetMsg_pop2 NetMsg_pop2;
//extern fp_3int bitmask;
//extern fp_1int bit_count;
//extern fp_2int intervention;
//extern fp_3int double_cross;
//extern fp_2int act_of_aggression;
//extern fp_3int steal_tech;
//extern fp_1int steal_energy;
extern fp_3int capture_base;
extern fp_1int clock_wait;
extern fp_2int sea_coast;
extern fp_1int sea_coasts;
extern fp_2int base_on_sea;
extern fp_1int base_coast;
extern fp_2int port_to_coast;
extern fp_2int port_to_port;
extern fp_1int transport_base;
extern fp_1int naval_base;
extern fp_2int convoy;
extern fp_1int mandate_color;

extern fp_1int random_events;
extern fp_none sub_5204E9;
extern fp_none alien_fauna;
extern fp_none do_fungal_towers;
extern fp_4int interlude;
extern fp_none set_time_controls;
extern fp_none reset_territory;
extern fp_1int sub_524340;
extern fp_2int generators;
extern fp_1int end_of_game;
extern fp_none turn_upkeep;
extern fp_1int repair_phase;
extern fp_1int allocate_energy;
extern fp_1int production_phase;
extern fp_1int faction_upkeep;
extern fp_none control_turn;
extern fp_1int net_upkeep_phase;
extern fp_none net_upkeep;
extern fp_none mash_planes;
extern fp_none net_end_of_turn;
extern fp_none net_control_turn;
extern fp_none control_game;
//extern fp_1int council_votes;
//extern fp_1int eligible;
extern fp_3int wants_prop;
extern fp_3int council_get_vote;
extern fp_2int council_action;
extern fp_2int can_call_council;
extern fp_1int call_council;
extern fp_none rebuild_vehicle_bits;
extern fp_none rebuild_base_bits;

extern fp_5int danger;
extern fp_1int checksum_file;
extern fp_3int checksum;
extern fp_1int checksum_password;
extern fp_none auto_contact;
//extern fp_4int net_treaty_on;
//extern fp_4int net_treaty_off;
//extern fp_5int net_set_treaty;
//extern fp_4int net_agenda_off;
//extern fp_5int net_set_agenda;
//extern Fnet_energy net_energy;
//extern Fnet_loan net_loan;
//extern fp_3int net_maps;
//extern Fnet_tech net_tech;
//extern fp_3int net_pact_ends;
//extern fp_3int net_cede_base;
//extern fp_4int net_double_cross;
extern fp_1int diplo_lock;
extern fp_none diplo_unlock;
extern fp_none sub_5398E0;
extern fp_none sub_539920;
extern fp_2int diplomacy_caption;
//extern fp_2int great_beelzebub;
//extern fp_2int great_satan;
//extern fp_2int aah_ooga;
//extern fp_none climactic_battle;
//extern fp_1int at_climax;
//extern fp_3int cause_friction;
//extern fp_1int get_mood;
//extern fp_2int reputation;
//extern fp_2int get_patience;
//extern fp_1int energy_value;
extern fp_2int mention_prototypes;
extern fp_2int scan_prototypes;
extern fp_4int contiguous;
extern fp_3int diplomacy_check;
extern fp_2int pact_withdraw;
extern fp_2int pact_ends;
extern fp_2int pact_of_brotherhood;
extern fp_2int make_treaty;
extern fp_3int pledge_truce;
extern fp_2int introduce;
extern fp_2int wants_to_speak;
extern fp_2int diplomacy_ends;
extern fp_2int demands_withdrawal;
extern fp_2int renounce_pact;
extern fp_2int tech_analysis;
extern fp_4int buy_council_vote;
extern fp_5int buy_tech;
extern fp_2int energy_trade;
extern fp_5int tech_trade;
extern fp_2int trade_maps;
extern fp_2int propose_pact;
extern fp_2int propose_treaty;
extern fp_2int propose_attack;
extern fp_2int make_gift;
extern fp_2int dont_withdrawal;
extern fp_2int do_withdrawal;
extern fp_2int demand_withdrawal;
extern fp_2int threaten;
extern fp_2int suggest_plan;
extern fp_2int attack_from;
extern fp_1int sub_54B140;
extern fp_2int battle_plans;
extern fp_2int call_off_vendetta;
extern fp_2int diplomacy_menu;
extern fp_5int value_of_base;
extern fp_2int give_a_base;
extern fp_2int base_swap;
extern fp_2int proposal_menu;
extern fp_3int make_a_proposal;
extern fp_3int communicate;
extern fp_2int commlink_attempter;
extern fp_1int commlink_attempt;

extern fp_1int pick_top_veh;
extern fp_7int veh_draw;
extern fp_5int veh_scoot;
extern Fbase_draw base_draw;
//extern fp_3int treaty_off;
//extern fp_3int agenda_off;
//extern fp_3int treaty_on;
//extern fp_3int agenda_on;
//extern fp_4int set_treaty;
//extern fp_4int set_agenda;
extern fp_1int spying;
extern fp_3int wants_to_attack;
extern fp_2int comm_check;
extern fp_2int enemies_war;
extern fp_2int pact_unpact;
extern fp_2int enemies_unpact;
extern fp_3int enemies_team_up;
extern fp_2int enemies_trade_tech;
extern fp_3int enemies_treaty;
extern fp_6int encounter;
extern fp_5int territory;
//extern fp_4int atrocity;
//extern fp_2int major_atrocity;
extern fp_3int break_treaty;
extern fp_1int enemy_diplomacy;
extern fp_4int go_to;
extern fp_1int garrison_check;
extern fp_1int defensive_check;
extern fp_2int guard_check;
extern fp_1int enemy_capabilities;
extern fp_1int enemy_strategy;
extern fp_4int set_course;
extern fp_3int assemble_passengers;
extern fp_2int can_convoy;
extern fp_3int good_sensor;
extern fp_5int can_terraform;
extern fp_5int compute_odds;
extern fp_3int alien_base;
extern fp_1int alien_move;
extern fp_5int air_power;
extern fp_1int enemy_planet_buster;
extern fp_3int get_there;
extern fp_5int coast_or_border;
extern fp_1int enemy_move;
extern fp_1int enemy_veh;
extern fp_1int enemy_turn;
//extern fp_1int rnd;
extern fp_2int cursor_dist;
extern fp_3int site_at;
extern fp_3int is_known;
extern fp_2int base_who;
extern fp_2int anything_at;
//extern fp_1int veh_top;
extern fp_1int veh_moves;
extern fp_1int proto_power;
//extern fp_2int is_port;
//extern fp_6int add_goal;
//extern fp_5int add_site;
extern fp_4int at_goal;
extern fp_4int at_site;
//extern fp_1int wipe_goals;
//extern fp_1int clear_goals;
//extern fp_5int del_site;
//extern fp_1int want_monolith;
extern fp_1int monolith;
extern fp_1int goody_box;
extern fp_2int valid_tech_leap;
extern fp_1int study_artifact;
extern Fheader_check header_check;
extern Fheader_write header_write;
//extern fp_2int arm_strat;
//extern fp_2int weap_strat;
//extern fp_2int weap_val;
//extern fp_2int arm_val;
//extern fp_2int armor_val;
//extern fp_3int transport_val;
extern fp_2int say_offense;
extern fp_2int say_defense;
extern Fsay_stats2 say_stats_3;
extern Fsay_stats2 say_stats_2;
extern fp_3int say_stats;
extern fp_1int clear_bunglist;
extern fp_2int sub_57DF30;
extern fp_6int is_bunged;
extern Fname_proto name_proto;
//extern fp_1int best_reactor;
extern fp_3int pick_chassis;
extern fp_3int weapon_budget;
extern fp_2int retire_proto;
extern fp_3int prune_protos;
extern Fpropose_proto propose_proto;
extern fp_1int abil_index;
extern fp_3int add_abil;
extern fp_1int consider_designs;
extern fp_2int design_new_veh;
extern fp_6int hq_list_draw;
extern fp_2int design_workshop;
extern fp_4int abil_cond;

//extern fp_none map_wipe;
//extern fp_3int alt_put_detail;
//extern fp_3int alt_set;
//extern fp_2int alt_natural;
//extern fp_3int alt_set_both;
//extern fp_2int elev_at;
//extern fp_3int climate_set;
//extern fp_3int temp_set;
//extern fp_3int owner_set;
//extern fp_3int site_set;
//extern fp_3int region_set;
//extern fp_3int rocky_set;
extern fp_3int using_set;
extern fp_3int lock_set;
extern fp_3int lock_map;
extern fp_3int unlock_map;
//extern fp_3int bit_put;
//extern fp_4int bit_set;
//extern fp_4int bit2_set;
//extern fp_3int code_set;
//extern fp_3int synch_bit;
extern fp_2int minerals_at;
extern fp_2int bonus_at;
extern fp_2int goody_at;
//extern fp_6int say_loc;
extern fp_2int site_radius;
//extern fp_3int find_landmark;
//extern fp_3int new_landmark;
//extern fp_3int valid_landmark;
//extern fp_2int kill_landmark;
extern fp_2int delete_landmark;
extern fp_none fixup_landmarks;
extern fp_none set_dirty;
extern fp_none sub_592AF0;
extern fp_4int message_veh;
extern fp_4int message_base;
extern fp_6int message_data;
extern fp_4int message_big_data;
extern fp_8int message_lock;
extern fp_7int message_landmark;
extern fp_3int message_chat;
extern fp_1int synch_veh;
extern fp_1int synch_base;
extern fp_1int synch_energy;
extern fp_1int synch_researching;
extern fp_1int synch_leader;
extern fp_1int synch_ai;
extern fp_1int synch_research;
extern fp_1int sub_593390;
extern fp_1int synch_soc;
extern fp_1int synch_proto;
extern fp_1int synch_obs;
extern fp_2int synch_diplo;
extern fp_1int sub_5934B0;
extern fp_1int synch_radius;
extern Fhex_cost hex_cost;
extern fp_7int quick_zoc;
extern fp_2int supply_options;
extern fp_3int order_veh;

//extern fp_1int tech_name;
//extern fp_1int chas_name;
//extern fp_1int weap_name;
//extern fp_1int arm_name;
//extern fp_none read_basic_rules;
//extern fp_none read_tech;
//extern fp_1int read_faction2;
//extern fp_2int read_faction;
//extern fp_none read_factions;
//extern fp_none read_units;
//extern fp_1int read_rules;
extern fp_none sub_5882D0;
extern fp_2int find_font;
extern fp_none scroll_normal;
extern fp_none scroll_small;
extern fp_none popups_normal;
extern fp_none popups_tutorial;
extern fp_none popups_medium;
extern fp_none config_popups;
extern fp_none alien_start;
extern fp_1int planetfall;
extern fp_1int time_controls_dialog;
extern fp_1int thumb_routine;
extern fp_1int change_opening;
extern fp_none close_opening;
extern fp_1int config_game;
extern fp_2int custom_planet;
extern fp_1int size_of_planet;
extern fp_1int map_menu;
extern fp_1int multiplayer_init;
extern fp_1int top_menu;
extern fp_1int desktop_init;
extern fp_none desktop_close;
extern fp_none system_init;
extern fp_none system_close;
extern fp_2int game_init;
extern fp_none game_close;
extern fp_2int game_reload;
extern fp_3int say_special;
extern fp_3int say_fac_special;
extern fp_2int get_phrase;
extern fp_2int get_noun_phrase;
extern fp_1int get_pact;
extern fp_1int get_pacts;
extern fp_2int get_pacts2;
extern fp_2int get_pact_hood;
extern fp_2int get_his_her;
extern fp_2int get_him_her;
extern fp_2int get_he_she;

//extern fp_3int prefs_get2;
//extern fp_none default_prefs;
//extern fp_none default_prefs2;
//extern fp_none default_warn;
//extern fp_none default_rules;
//extern fp_3int prefs_get;
//extern fp_none prefs_fac_load;
//extern fp_1int prefs_load;
//extern fp_2int prefs_put2;
//extern fp_3int prefs_put;
//extern fp_1int prefs_save;
//extern fp_none prefs_use;
//extern fp_3int vulnerable;
extern fp_3int mind_control;
//extern fp_1int corner_market;
extern fp_4int success_rates;
extern fp_4int probe;
extern fp_2int sub_5A58E0;
extern fp_none sub_5A5900;
extern fp_4int sub_5A5910;
extern fp_1int sub_5A5990;
//extern fp_3int veh_put;
extern fp_1int veh_health;
extern fp_5int proto_cost;
extern fp_1int base_cost;
extern fp_6int make_proto;
extern fp_1int proto_sort;
extern fp_1int proto_sort_2;
extern fp_3int radius_move;
extern fp_5int radius_move2;
extern fp_4int compass_move;
extern fp_4int encrypt_write;
extern fp_4int encrypt_read;
extern fp_2int game_io;
extern fp_2int game_data;
extern fp_3int map_data;
extern FGenString save_daemon;
extern fp_none see_map_check;
extern Fload_daemon load_daemon;
extern FGenString save_map_daemon;
extern FGenString load_map_daemon;
extern fp_1int yearmotize;
extern fp_1int save_game;
extern fp_2int load_game;
extern fp_none load_map;
extern fp_none save_map;
extern fp_none kill_auto_save;
extern fp_none auto_save;
extern fp_1int load_undo;
extern fp_none wipe_undo;
extern fp_none auto_undo;
extern fp_2int sub_5ABFF0;
//extern fp_1int is_objective;
extern fp_2int num_objectives;
extern fp_2int most_objectives;
extern fp_none ascending;
extern fp_1int rankings;
extern fp_4int compute_score;
extern fp_none show_replay;

extern fp_1int crash_landing;
extern fp_none time_warp;
extern fp_none balance;
extern fp_none scenario_setup;
extern fp_1int sub_5B0D70;
extern fp_3int setup_player;
extern fp_2int eliminate_player;
extern fp_none clear_scenario;
extern fp_1int setup_game;
//extern fp_5int social_calc;
//extern fp_1int social_upkeep;
//extern fp_2int social_upheaval;
extern fp_1int social_set;
//extern fp_3int society_avail;
extern fp_6int social_ai;
extern fp_1int social_select;
//extern fp_3int sort;
extern fp_3int sub_5B5700;
extern fp_2int spot_base;
extern fp_2int spot_stack;
extern fp_1int unspot_stack;
extern fp_3int spot_loc;
extern fp_3int want_to_wake;
extern fp_1int wake_stack;
extern fp_2int spot_all;
extern fp_3int stack_put;
//extern fp_1int stack_sort;
extern fp_1int stack_sort2;
//extern fp_1int stack_fix;
extern fp_2int stack_veh;
extern fp_1int stack_kill;
extern fp_5int stack_check;
//extern fp_void g_WAVE_ctor;
//extern fp_void g_WAVE_dtor;
//extern fp_3int say_tech;
extern fp_2int tech_name2;
//extern fp_2int has_tech;
extern fp_2int tech_recurse;
//extern fp_1int tech_category;
//extern fp_2int redundant;
extern fp_4int facility_avail;
extern fp_3int veh_avail;
extern fp_3int terrain_avail;
extern fp_2int tech_avail;
extern fp_1int tech_effects;
extern fp_4int tech_achieved;
//extern fp_3int tech_is_preq;
extern fp_3int tech_val;
extern fp_1int tech_ai;
extern fp_1int tech_mil;
extern fp_1int tech_tech;
extern fp_1int tech_infra;
extern fp_1int tech_colonize;
extern fp_2int wants_prototype;
extern fp_1int tech_selection;
extern fp_1int tech_advance;
extern fp_1int tech_rate;
extern fp_2int tech_research;
extern fp_4int tech_pick;
extern fp_2int X_text_open;
extern fp_3int do_unity_crash;

//extern fp_2int veh_at;
//extern fp_1int veh_lift;
//extern fp_3int veh_drop;
//extern fp_1int sleep;
//extern fp_1int veh_demote;
//extern fp_1int veh_promote;
//extern fp_3int veh_clear;
extern fp_4int veh_init;
extern fp_1int veh_kill;
extern fp_1int kill;
extern fp_4int veh_find;
//extern fp_2int can_arty;
extern fp_3int morale_veh;
extern fp_3int offense_proto;
extern fp_3int armor_proto;
extern fp_1int speed_proto; // replaced by proto_speed
extern fp_2int speed; // replaced by veh_speed
//extern fp_1int veh_cargo;
//extern fp_1int prototype_factor;
extern Fveh_cost veh_cost;
extern fp_1int veh_selectable;
extern fp_1int veh_unmoved;
extern fp_1int veh_ready;
extern fp_1int veh_jail;
extern fp_1int veh_skip;
extern fp_2int veh_fake;
extern fp_1int veh_wake;

//extern fp_4int world_alt_set;
//extern fp_2int world_raise_alt;
//extern fp_2int world_lower_alt;
extern fp_3int brush;
extern fp_4int paint_land;
extern fp_1int build_continent;
extern fp_1int build_hills;
extern fp_none world_erosion;
extern fp_none world_rocky;
extern fp_none world_fungus;
extern fp_none world_riverbeds;
extern fp_none world_rivers;
extern fp_none world_shorelines;
extern fp_none world_validate;
extern fp_none world_temperature;
extern fp_none world_rainfall;
extern fp_3int world_site;
extern fp_none world_analysis;
extern fp_none world_polar_caps;
extern fp_none world_climate;
extern fp_none world_linearize_contours;
//extern fp_2int near_landmark;
extern fp_2int world_crater;
extern fp_2int world_monsoon;
extern fp_2int world_sargasso;
extern fp_2int world_ruin;
extern fp_2int world_dune;
extern fp_2int world_diamond;
extern fp_2int world_fresh;
extern fp_3int world_volcano;
extern fp_2int world_borehole;
extern fp_2int world_temple;
extern fp_2int world_unity;
extern fp_2int world_fossil;
extern fp_2int world_canyon;
extern fp_2int world_mesa;
extern fp_2int world_ridge;
extern fp_2int world_geothermal;
extern fp_none world_build;
//extern fp_1int game_year;
extern fp_1int say_year;
extern fp_3int zoc_any;
extern fp_3int zoc_veh;
extern fp_3int zoc_sea;
extern fp_3int zoc_move;

typedef int(__cdecl *Ftext_open)(const char* filename, const char* label);
typedef int(__cdecl *Fparse_string)(char* src, char* dst);
typedef char*(__cdecl *Ftext_item)();
typedef char*(__cdecl *Ffilefind_get)(const char* text);
typedef int(__thiscall *Fset_bubble_text)(void* This, const char* name);
typedef int(__thiscall *FStrings)(void* This);
typedef int(__thiscall *FStrings_init)(void* This, size_t len);
typedef int(__thiscall *FStrings_shutdown)(void* This);
typedef char*(__thiscall *FStrings_put)(void* This, char* text);
typedef char*(__thiscall *FStrings_get)(void* This, char* text);

extern FGenString Win_init_class;
extern fp_none wait_task;
extern fp_none do_task;
extern fp_none do_all_tasks;
extern fp_1int do_all_tasks2;
extern fp_none do_non_input;
extern fp_none do_all_non_input;
extern fp_none do_draw;
extern fp_none do_all_draws;
extern fp_none sub_5FCFE0;
extern fp_none flush_input;
extern fp_none do_sound;
extern fp_none flush_timer;
//extern fp_none text_shutdown;
//extern fp_none text_dtor;
//extern fp_none text_close;
//extern Ftext_open text_open;
//extern fp_none text_get;
//extern fp_none text_string;
//extern Ftext_item text_item;
//extern Ftext_item text_item_string;
//extern fp_none text_item_number;
//extern fp_none text_item_binary;
extern FGenString text_make_index;
extern Ftext_open text_search_index;
extern fp_none text_clear_index;
extern fp_1int filefind_set_alternative;
extern fp_2int filefind_init;
extern Ffilefind_get filefind_get;
extern FStrings Strings_Strings;
extern FStrings_init Strings_init;
extern FStrings Strings_shutdown;
extern FStrings_put Strings_put;
extern FStrings_get Strings_get;
extern FStrings Strings_dtor;
extern fp_none labels_shutdown;
extern fp_none labels_init;
extern Fparse_string parse_string;
//extern fp_2int parse_num;
extern fp_4int parse_say;
//extern fp_4int parse_says;

#pragma GCC diagnostic pop



