#pragma once
#pragma pack(push, 1)


struct GamePrefs {
    int32_t GamePreferences;
    int32_t GameMorePreferences;
    int32_t GameWarnings;
    int32_t GameRules;
    int32_t dword_9A64A0;
    int32_t GameInterludeState[2];
    int32_t dword_9A64AC;
    int32_t dword_9A64B0;
    int32_t TutWinMapState;
    int32_t dword_9A64B8;
    int32_t dword_9A64BC;
    int32_t GameState;
    int32_t DiffLevel;
    int32_t VehCount;
    int32_t BaseCount;
    int32_t dword_9A64D0;
    int32_t CurrentTurn;
    int32_t CurrentMissionYear;
    int32_t CurrentVehID;
    int32_t GameTimeControl[2];
    uint8_t FactionStatus[4];
    int32_t FactionRankings[8];
    int32_t RankingFactionIDUnk1;
    int32_t RankingFactionIDUnk2;
    int32_t SecretProjects[64];
    int32_t GovernorFaction;
    int32_t ProposalPassCount[11];
    int32_t ProposalCallTurn[11];
    uint8_t TechOwners[89];
    char    LastSavePath[256];
    uint8_t pad0[3];
    int32_t ClimateValueA;
    int32_t ClimateValueB;
    int32_t ClimateValueC;
    int32_t ClimateFutureChange;
    int32_t dword_9A67DC;
    int32_t dword_9A67E0[8];
    int32_t SunspotDuration;
    int32_t MountPlanetX;
    int32_t MountPlanetY;
    int32_t DustCloudDuration;
    int32_t SaveFileVersion;
    int32_t ScnVictFacilityObj;
    int32_t SolarFlaresEvent;
    int32_t GameMoreRules;
    int32_t CurrentFaction;
    int32_t ClimateLevel;
};

struct LegacyGamePrefs {
    uint8_t GamePrefs[132];
    uint8_t SecretProjects[132];
    int32_t GovernorFaction;
    int32_t ProposalPassCount[11];
    int32_t ProposalCallTurn[11];
    uint8_t TechOwners[89];
    char    LastSavePath[256];
    uint8_t pad0[3];
    int32_t ClimateValueA;
    int32_t ClimateValueB;
    int32_t ClimateValueC;
    int32_t ClimateFutureChange;
    int32_t dword_9A67DC;
    uint8_t dword_9A67E0[32];
    int32_t SunspotDuration;
    int32_t MountPlanetX;
    int32_t MountPlanetY;
    int32_t DustCloudDuration;
    int32_t SaveFileVersion;
    int32_t ScnVictFacilityObj;
    int32_t SolarFlaresEvent;
    int32_t GameMoreRules;
    int32_t CurrentFaction;
    int32_t ClimateLevel;
};

struct LegacyFactionV10 {
    // same as the current Faction from here down to facility_announced
    int32_t player_flags;
    int32_t ranking;
    int32_t diff_level;
    int32_t base_name_offset;
    int32_t base_sea_name_offset;
    int32_t last_base_turn;
    int32_t diplo_status[8];
    int32_t diplo_agenda[8];
    int32_t diplo_friction[8];
    int32_t diplo_spoke[8];
    int32_t diplo_merc[8];
    int8_t  diplo_patience[8];
    int32_t sanction_turns;
    int32_t loan_balance[8];
    int32_t loan_payment[8];
    int32_t unk_1[8];
    int32_t integrity_blemishes;
    int32_t diplo_reputation;
    int32_t diplo_gifts[8];
    int32_t diplo_wrongs[8];
    int32_t diplo_betrayed[8];
    int32_t diplo_unk_3[8];
    int32_t diplo_unk_4[8];
    int32_t traded_maps;
    int32_t base_governor_adv;
    int32_t atrocities;
    int32_t major_atrocities;
    int32_t mind_control_total;
    int32_t diplo_mind_control[8];
    int32_t diplo_stolen_techs[8];
    int32_t energy_credits;
    int32_t hurry_cost_total;
    int32_t SE_Politics_pending;
    int32_t SE_Economics_pending;
    int32_t SE_Values_pending;
    int32_t SE_Future_pending;
    int32_t SE_Politics;
    int32_t SE_Economics;
    int32_t SE_Values;
    int32_t SE_Future;
    int32_t SE_upheaval_cost_paid;
    int32_t SE_economy_pending;
    int32_t SE_effic_pending;
    int32_t SE_support_pending;
    int32_t SE_talent_pending;
    int32_t SE_morale_pending;
    int32_t SE_police_pending;
    int32_t SE_growth_pending;
    int32_t SE_planet_pending;
    int32_t SE_probe_pending;
    int32_t SE_industry_pending;
    int32_t SE_research_pending;
    int32_t SE_economy;
    int32_t SE_effic;
    int32_t SE_support;
    int32_t SE_talent;
    int32_t SE_morale;
    int32_t SE_police;
    int32_t SE_growth;
    int32_t SE_planet;
    int32_t SE_probe;
    int32_t SE_industry;
    int32_t SE_research;
    int32_t SE_economy_2;
    int32_t SE_effic_2;
    int32_t SE_support_2;
    int32_t SE_talent_2;
    int32_t SE_morale_2;
    int32_t SE_police_2;
    int32_t SE_growth_2;
    int32_t SE_planet_2;
    int32_t SE_probe_2;
    int32_t SE_industry_2;
    int32_t SE_research_2;
    int32_t SE_economy_base;
    int32_t SE_effic_base;
    int32_t SE_support_base;
    int32_t SE_talent_base;
    int32_t SE_morale_base;
    int32_t SE_police_base;
    int32_t SE_growth_base;
    int32_t SE_planet_base;
    int32_t SE_probe_base;
    int32_t SE_industry_base;
    int32_t SE_research_base;
    int32_t energy_surplus_total;
    int32_t facility_maint_total;
    int32_t tech_commerce_bonus;
    int32_t turn_commerce_income;
    int32_t unk_17;
    int32_t unk_18;
    int32_t tech_fungus_nutrient;
    int32_t tech_fungus_mineral;
    int32_t tech_fungus_energy;
    int32_t tech_fungus_unused;
    int32_t SE_alloc_psych;
    int32_t SE_alloc_labs;
    int32_t tech_pact_shared_goals[12];
    int32_t tech_ranking;
    int32_t unk_27;
    int32_t ODP_deployed;
    int32_t tech_count_transcendent;
    int8_t  tech_trade_source[92];
    int32_t tech_accumulated;
    int32_t tech_research_id;
    int32_t tech_cost;
    int32_t earned_techs_saved;
    int32_t net_random_event;
    int32_t AI_fight;
    int32_t AI_growth;
    int32_t AI_tech;
    int32_t AI_wealth;
    int32_t AI_power;
    int32_t target_x;
    int32_t target_y;
    int32_t best_mineral_output;
    int32_t council_call_turn;
    int32_t unk_29[11];
    int32_t unk_30[11];
    // diverges from the current Faction starting here
    uint8_t  facility_announced[8]; // current: uint32_t[12]
    int32_t  clean_minerals_modifier;
    int32_t  base_id_attack_target;
    int32_t  unk_37;
    char     saved_queue_name[8][24];
    int32_t  saved_queue_size[8];
    int32_t  saved_queue_items[8][10];
    int32_t  social_support[8];
    int32_t  social_psych[8][9];
    int32_t  social_effic[9];
    int32_t  unk_45;
    int32_t  unk_46;
    int32_t  unk_47;
    int32_t  nutrient_surplus_total;
    int32_t  labs_total;
    int32_t  satellites_nutrient;
    int32_t  satellites_mineral;
    int32_t  satellites_energy;
    int32_t  satellites_ODP;
    int32_t  best_weapon_value;
    int32_t  best_psi_land_offense;
    int32_t  best_psi_land_defense;
    int32_t  best_armor_value;
    int32_t  best_land_speed;
    int32_t  enemy_best_weapon_value;
    int32_t  enemy_best_armor_value;
    int32_t  enemy_best_land_speed;
    int32_t  enemy_best_psi_land_offense;
    int32_t  enemy_best_psi_land_defense;
    int32_t  unk_64;
    int32_t  unk_65;
    int32_t  unk_66;
    int32_t  unk_67;
    int32_t  unk_68;
    int32_t  unk_69;
    uint8_t  units_active[512];
    uint8_t  units_queue[512];
    uint16_t units_lost[512];
    int32_t  total_combat_units;
    int32_t  base_count;
    int32_t  mil_strength_1;
    int32_t  mil_strength_2;
    int32_t  pop_total;
    int32_t  unk_70;
    int32_t  planet_busters;
    int32_t  unk_71;
    int32_t  unk_72;
    uint16_t region_total_combat_units[128];
    uint8_t  region_total_bases[128];
    uint8_t  region_total_offensive_units[128];
    uint16_t region_force_rating[128];
    uint16_t region_flags[128];
    uint16_t region_territory_tiles[128];
    uint16_t region_visible_tiles[128];
    uint16_t region_good_tiles[128];
    uint16_t region_unk_5[128];
    uint8_t  region_unk_6[128];
    uint8_t  region_territory_pods[128];
    uint8_t  region_base_plan[128];
    Goal     goals[75];
    Goal     sites[25];
    int32_t  unk_93;
    int32_t  goody_opened;
    int32_t  goody_artifact;
    int32_t  goody_earthquake;
    int32_t  goody_tech;
    int32_t  tech_achieved;
    int32_t  time_bonus_count;
    int32_t  unk_99;
    uint32_t secret_project_intel[5]; // current: uint32_t[8]
    int32_t  corner_market_turn;
    int32_t  corner_market_cost;
    int32_t  unk_101;
    int32_t  unk_102;
    int32_t  unk_103;
    int32_t  player_flags_ext;
    int32_t  unk_105;
    int32_t  unk_106;
    int32_t  unk_107;
    int32_t  eliminated_count;
    int32_t  unk_109;
    int32_t  unk_110;
    int32_t  unk_111;
    int32_t  unk_112;
    int32_t  unk_113;
    int32_t  unk_114;
    int32_t  unk_115;
    int32_t  unk_116;
    int32_t  unk_117;
    int32_t  unk_118;
};

struct LegacyFactionV2 {
    uint8_t  common_head[2132];
    uint8_t  units_active[256];
    uint8_t  units_queue[256];
    uint16_t units_lost[256];
    uint8_t  common_tail[4200];
};

struct LegacyVehV2 {
    int16_t  x;
    int16_t  y;
    uint32_t state;
    uint16_t flags;
    uint8_t  unit_id; // current: int16_t
    uint8_t  faction_id;
    uint8_t  damage_taken;
    uint8_t  order;
    uint8_t  waypoint_count;
    uint8_t  patrol_current_point;
    int16_t  waypoint_x[4];
    int16_t  waypoint_y[4];
    uint8_t  morale;
    uint8_t  movement_turns;
    uint8_t  order_auto_type;
    uint8_t  visibility;
    uint8_t  moves_spent;
    int8_t   rotate_angle;
    uint8_t  iter_count;
    uint8_t  status_icon;
    uint8_t  probe_action;
    uint8_t  probe_sabotage_id;
    int16_t  home_base_id;
    int16_t  next_veh_id_stack;
    int16_t  prev_veh_id_stack;
};

struct LegacyBaseV2 {
    int16_t x;
    int16_t y;
    int8_t  faction_id;
    int8_t  faction_id_former;
    int8_t  pop_size;
    uint8_t assimilation_turns_left;
    uint8_t nerve_staple_turns_left;
    uint8_t ai_plan_status;
    uint8_t visibility;
    int8_t  factions_pop_size_intel[8];
    char    name[25];
    int16_t unk_x;
    int16_t unk_y;
    int32_t state_flags;
    int32_t event_flags;
    int32_t governor_flags;
    int32_t nutrients_accumulated;
    int32_t minerals_accumulated;
    int32_t production_id_last;
    int32_t eco_damage;
    int32_t queue_size;
    int32_t queue_items[10];
    int32_t worked_tiles;
    int32_t specialist_total;
    int32_t specialist_adjust;
    int32_t specialist_types[2];
    uint8_t facilities_built[8]; // current: uint8_t[12]
    int32_t mineral_surplus_final;
    int32_t minerals_accumulated_2;
    int32_t pad_1;
    int32_t pad_2;
    int32_t pad_3;
    int32_t pad_4;
    int32_t nutrient_intake;
    int32_t mineral_intake;
    int32_t energy_intake;
    int32_t unused_intake;
    int32_t nutrient_intake_2;
    int32_t mineral_intake_2;
    int32_t energy_intake_2;
    int32_t unused_intake_2;
    int32_t nutrient_surplus;
    int32_t mineral_surplus;
    int32_t energy_surplus;
    int32_t unused_surplus;
    int32_t nutrient_inefficiency;
    int32_t mineral_inefficiency;
    int32_t energy_inefficiency;
    int32_t unused_inefficiency;
    int32_t nutrient_consumption;
    int32_t mineral_consumption;
    int32_t energy_consumption;
    int32_t unused_consumption;
    int32_t economy_total;
    int32_t psych_total;
    int32_t labs_total;
    int32_t unk_total;
    int16_t autoforward_land_base_id;
    int16_t autoforward_sea_base_id;
    int16_t autoforward_air_base_id;
    int16_t pad_5;
    int32_t talent_total;
    int32_t drone_total;
    int32_t superdrone_total;
    int32_t random_event_turns;
    int32_t nerve_staple_count;
    int32_t pad_7;
    int32_t pad_8;
};

static_assert(sizeof(GamePrefs) == 0x398, "");
static_assert(sizeof(LegacyGamePrefs) == 0x31C, "");
static_assert(offsetof(GamePrefs, SaveFileVersion) == 0x380, "");

static_assert(sizeof(LegacyFactionV10) == 0x20BC, "");
static_assert(offsetof(LegacyFactionV10, facility_announced) == 0x458, "");
static_assert(offsetof(LegacyFactionV10, clean_minerals_modifier) == 0x460, "");
static_assert(offsetof(LegacyFactionV10, secret_project_intel) == 0x2058, "");
static_assert(sizeof(LegacyFactionV2) == 0x1CBC, "");
static_assert(sizeof(LegacyFactionV2::common_tail) ==
    sizeof(LegacyFactionV10) - offsetof(LegacyFactionV10, total_combat_units), "");
static_assert(offsetof(LegacyFactionV2, common_tail) == 0xC54, "");
static_assert(sizeof(LegacyVehV2) == 0x30, "");
static_assert(sizeof(LegacyBaseV2) == 0x130, "");


#pragma pack(pop)
